// Level O Questions (storyIds 147-157) - Real, story-specific comprehension questions

// Story 147: River Rapids (O) - Fiction
// IDs 2831-2842
            { id: 2831, storyId: 147, category: "theme", type: "multiple", question: "What is the main theme of 'River Rapids'?", options: ["Working together and trusting each other to overcome challenges", "The importance of wearing life jackets while canoeing", "Learning to swim in rough water", "Why rivers are dangerous places to visit"], correct: 0, hint: "Think about how Marcus and Destiny got through the rapids.", explanation: "The story shows that teamwork and trust helped Marcus and Destiny survive the dangerous rapids!" },
            { id: 2832, storyId: 147, category: "inference", type: "multiple", question: "Why were Marcus and Destiny able to paddle 'in perfect synchronization'?", options: ["They were professional river guides", "They had never been in a canoe before", "They had practiced together for months", "Their instructor was paddling with them"], correct: 2, hint: "The story mentions something about their practice.", explanation: "The text says 'their months of practice finally paying off,' showing they had trained together!" },
            { id: 2833, storyId: 147, category: "vocabulary", type: "multiple", question: "What does 'lurched' mean when the passage says 'The canoe lurched violently'?", options: ["Floated gently downstream", "Moved suddenly and unsteadily", "Sank slowly underwater", "Spun in a complete circle"], correct: 1, hint: "Think about what happens when you hit unexpected rapids.", explanation: "'Lurched' means to make a sudden, unsteady movement, like when the canoe hit the rapids!" },
            { id: 2834, storyId: 147, category: "sequence", type: "multiple", question: "What happened AFTER Marcus steered the canoe hard right to avoid the boulder?", options: ["They immediately reached calm water", "Marcus remembered his instructor's words", "Destiny spotted where the river narrowed between canyon walls", "They capsized in the water"], correct: 2, hint: "The boulder was the first obstacle, but there were more ahead.", explanation: "After avoiding the boulder, Destiny pointed out that the river narrowed between canyon walls ahead!" },
            { id: 2835, storyId: 147, category: "character", type: "multiple", question: "What character trait does Marcus show when he makes a 'split-second decision' to steer right?", options: ["He is indecisive and unsure", "He is quick-thinking and decisive under pressure", "He is reckless and careless", "He is frightened and panicking"], correct: 1, hint: "Think about how Marcus reacts in the moment of danger.", explanation: "Marcus shows he can think and act quickly under pressure, making a fast decision that saves them!" },
            { id: 2836, storyId: 147, category: "main_idea", type: "multiple", question: "What is the main idea of 'River Rapids'?", options: ["Marcus and Destiny use teamwork and skill to navigate dangerous rapids together", "Canoeing is a popular outdoor sport for siblings", "Rivers can change from calm to dangerous without warning", "Marcus learns how to steer a canoe for the first time"], correct: 0, hint: "What is the most important thing that happens in this story?", explanation: "The story is mainly about how Marcus and Destiny work together to safely navigate through the rapids!" },
            { id: 2837, storyId: 147, category: "cause_effect", type: "multiple", question: "What caused Marcus to look for a V-shape pointing downstream?", options: ["Destiny told him to look for one", "He saw a sign posted on the canyon wall", "He remembered his kayaking instructor's advice", "He read about it in a book that morning"], correct: 2, hint: "Where did Marcus learn about reading the water?", explanation: "Marcus remembered his instructor's words: 'Look for V-shapes pointing downstream--that's your safe path!'" },
            { id: 2838, storyId: 147, category: "compare_contrast", type: "multiple", question: "How is the beginning of the canoe trip different from the middle?", options: ["It starts on a lake and moves to a river", "It starts peaceful and becomes dangerous", "It starts at night and becomes daytime", "It starts with three people and ends with two"], correct: 1, hint: "Think about how the passage describes the afternoon before the rapids.", explanation: "The story contrasts their 'peaceful afternoon' with the sudden dangerous rapids they encounter!" },
            { id: 2839, storyId: 147, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Canoeing is the most exciting water sport", "The rapids were the scariest thing Marcus had ever seen", "Water splashed over the sides, soaking their supplies", "Destiny was the best paddler on the river"], correct: 2, hint: "Which statement describes something that actually happened without adding personal judgment?", explanation: "The passage directly states that water splashed over the sides and soaked their supplies!" },
            { id: 2840, storyId: 147, category: "author_purpose", type: "multiple", question: "Why did the author include the detail about Marcus remembering his kayaking instructor?", options: ["To show that past learning can help in real emergencies", "To advertise kayaking classes", "To explain why Marcus doesn't like kayaking", "To show that Marcus has a bad memory"], correct: 0, hint: "How does remembering the instructor help Marcus in this moment?", explanation: "The author shows that what Marcus learned in training directly helped him find the safe path through the rapids!" },
            { id: 2841, storyId: 147, category: "text_structure", type: "multiple", question: "How is 'River Rapids' organized?", options: ["As a chronological action sequence with rising tension and resolution", "As a comparison between canoeing and kayaking", "As a list of safety rules for river travel", "As a flashback to a past adventure"], correct: 0, hint: "Think about how the events build from calm to dangerous to safe again.", explanation: "The story follows a timeline with rising action (hitting rapids, avoiding obstacles) leading to resolution (reaching calm water)!" },
            { id: 2842, storyId: 147, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Marcus made a split-second decision, steering hard right.", answers: {"0": "noun", "1": "verb", "3": "adjective", "4": "noun"}, hint: "Look for who does the action, what the action is, and what describes the noun.", explanation: "Marcus is a noun (name), made is a verb (action), split-second is an adjective (describes decision), and decision is a noun (thing)!" },

// Story 148: The New Kid's Secret (O) - Fiction
// IDs 2843-2854
            { id: 2843, storyId: 148, category: "theme", type: "multiple", question: "What is the main theme of 'The New Kid's Secret'?", options: ["School cafeterias should have better food", "People should not judge others before understanding them", "Art class is the most important subject", "Being new at school is always fun"], correct: 1, hint: "Think about how the other kids misunderstood Sofia and what Ethan discovered.", explanation: "The story teaches that we shouldn't judge others without understanding their situation first!" },
            { id: 2844, storyId: 148, category: "inference", type: "multiple", question: "Why did Sofia always sit in the front row of class?", options: ["She wanted to impress the teacher", "She couldn't see the board from far away", "She needed to read the teacher's lips since she is deaf", "She always arrived early to class"], correct: 2, hint: "Think about what Ethan learned about Sofia and how she communicates.", explanation: "Since Sofia is deaf and reads lips, sitting in the front row helped her understand what the teacher was saying!" },
            { id: 2845, storyId: 148, category: "vocabulary", type: "multiple", question: "What does 'hyperrealistic' mean when describing Sofia's drawing?", options: ["Extremely lifelike and detailed", "Brightly colored and abstract", "Quickly sketched and rough", "Copied from a photograph"], correct: 0, hint: "The passage says the drawing captured 'every detail' of their teacher.", explanation: "'Hyperrealistic' means extremely realistic--the drawing looked almost like a photograph!" },
            { id: 2846, storyId: 148, category: "sequence", type: "multiple", question: "What did Ethan do BEFORE he brought his lunch to the art room?", options: ["He learned sign language", "He noticed Sofia sitting alone drawing in the art room", "He talked to Sofia about her deafness", "He introduced Sofia to his friends"], correct: 1, hint: "What first caught Ethan's attention about Sofia?", explanation: "Ethan first noticed Sofia sitting alone in the art room with her sketchpad, then decided to bring his lunch there the next day!" },
            { id: 2847, storyId: 148, category: "character", type: "multiple", question: "What character trait does Ethan show throughout this story?", options: ["He is nosy and gossipy", "He is kind and willing to make an effort to connect", "He is shy and avoids new people", "He is competitive and wants to be the best artist"], correct: 1, hint: "Think about how Ethan approaches Sofia compared to the other kids.", explanation: "Ethan shows kindness by sitting with Sofia, appreciating her art, and learning sign language to communicate with her!" },
            { id: 2848, storyId: 148, category: "main_idea", type: "multiple", question: "What is the main idea of 'The New Kid's Secret'?", options: ["Ethan befriends Sofia by taking time to understand her instead of believing rumors", "Sofia is the best artist in the school", "New students should always eat lunch alone", "Ethan wants to learn how to draw"], correct: 0, hint: "What is the most important thing that happens between Ethan and Sofia?", explanation: "The story is about Ethan making the effort to understand Sofia rather than believing the rumors about her!" },
            { id: 2849, storyId: 148, category: "cause_effect", type: "multiple", question: "What caused the other kids to think Sofia was arrogant?", options: ["She bragged about her artistic talent", "She never spoke in class and they didn't understand why", "She refused to share her drawings", "She told them she didn't want to be friends"], correct: 1, hint: "What did the other kids not know about Sofia?", explanation: "Because the kids didn't know Sofia was deaf, they misinterpreted her silence as arrogance!" },
            { id: 2850, storyId: 148, category: "compare_contrast", type: "multiple", question: "How does Ethan's approach to Sofia differ from the other students' approach?", options: ["Ethan spreads rumors while others are kind to her", "Ethan ignores her while others try to talk to her", "Ethan makes the effort to sit with her while others gossip and avoid her", "Ethan tells the teacher while others keep quiet"], correct: 2, hint: "Compare what the other kids do (spread rumors) with what Ethan does.", explanation: "While other students whispered rumors and avoided Sofia, Ethan sat with her and took the time to understand her!" },
            { id: 2851, storyId: 148, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Sofia was the most talented artist in the school", "Ethan was the nicest kid in class", "Sofia had transferred from a school three states away", "The art room was the best place to eat lunch"], correct: 2, hint: "Which statement can be verified directly from the text?", explanation: "The passage directly states that Sofia 'had transferred from a school three states away'!" },
            { id: 2852, storyId: 148, category: "author_purpose", type: "multiple", question: "Why did the author include the detail about rumors swirling around Sofia?", options: ["To show how people make wrong assumptions when they don't understand someone", "To make Sofia seem like a mysterious villain", "To explain why the school has a gossip problem", "To show that rumors are always true"], correct: 0, hint: "What do the rumors reveal about how people treat what they don't understand?", explanation: "The author uses the rumors to show how quickly people misjudge others when they don't take time to understand!" },
            { id: 2853, storyId: 148, category: "text_structure", type: "multiple", question: "How is 'The New Kid's Secret' organized?", options: ["As a problem-solution story where curiosity leads to understanding", "As a debate about whether deaf students should attend regular schools", "As a list of tips for making new friends", "As a comparison between art and language"], correct: 0, hint: "Think about the problem (misunderstanding) and how it gets resolved.", explanation: "The story follows a problem-solution structure: the problem of misunderstanding Sofia is solved when Ethan takes the time to connect!" },
            { id: 2854, storyId: 148, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Sofia smiled shyly and wrote on paper.", answers: {"0": "noun", "1": "verb", "2": "adverb", "5": "noun"}, hint: "Look for who does the action, what the actions are, how an action is done, and the thing.", explanation: "Sofia is a noun (name), smiled is a verb (action), shyly is an adverb (how she smiled), and paper is a noun (thing)!" },

// Story 149: The Whispering Woods (O) - Fiction
// IDs 2855-2866
            { id: 2855, storyId: 149, category: "theme", type: "multiple", question: "What is the main theme of 'The Whispering Woods'?", options: ["Magic is dangerous and should be avoided", "Adventure can be found close to home when you're open to it", "Old maps are always valuable and should be collected", "Garage sales are good places to find treasure"], correct: 1, hint: "Think about where the treasure map leads Kai.", explanation: "The story shows that adventure and magic can be found close to home--the treasure is only two miles away in Henderson Park!" },
            { id: 2856, storyId: 149, category: "inference", type: "multiple", question: "Who do you think Kai is going to call at the end of the story?", options: ["The police to report the map", "The garage sale owner to return the map", "A friend who would believe in the map's magic", "A teacher to explain the map"], correct: 2, hint: "The map says 'Bring the one who believes.' Who would Kai trust with this?", explanation: "The map whispers 'Bring the one who believes,' and Kai 'knew exactly who to call'--likely a close friend who would believe in magic!" },
            { id: 2857, storyId: 149, category: "vocabulary", type: "multiple", question: "What does 'corresponded' mean when the passage says the three rivers 'corresponded to three creeks'?", options: ["Were completely different from", "Matched up with or were equivalent to", "Were bigger and wider than", "Sent letters to"], correct: 1, hint: "Kai compared the map to satellite images. What did he find?", explanation: "'Corresponded' means matched or were equivalent to--the three rivers on the map matched the three creeks in real life!" },
            { id: 2858, storyId: 149, category: "sequence", type: "multiple", question: "What happened AFTER Kai noticed the map was changing before his eyes?", options: ["He bought the map for fifty cents", "He heard the map whisper his name for the first time", "He grabbed his phone and compared it to satellite images of his town", "He called his friend immediately"], correct: 2, hint: "Once Kai saw the new glowing paths and the red X, what did he do next?", explanation: "After seeing the map change, Kai grabbed his phone and compared the map to satellite images to figure out the location!" },
            { id: 2859, storyId: 149, category: "character", type: "multiple", question: "What character traits does Kai display in this story?", options: ["He is fearful and avoids anything unusual", "He is curious, adventurous, and resourceful", "He is greedy and only wants treasure for money", "He is bored and uninterested in the map"], correct: 1, hint: "Think about how Kai reacts to the whispering map and what he does with it.", explanation: "Kai shows curiosity by buying the map, adventure by following its clues, and resourcefulness by using satellite images!" },
            { id: 2860, storyId: 149, category: "main_idea", type: "multiple", question: "What is the main idea of 'The Whispering Woods'?", options: ["A boy finds a magical, whispering map that leads to a treasure hidden near his own home", "Kai collects old maps as a hobby", "Garage sales are great places to find unusual items", "Kai is afraid of mysterious maps"], correct: 0, hint: "What is the most important thing that happens in the story?", explanation: "The story is about Kai discovering a magical map that whispers clues and leads to a treasure in his own neighborhood!" },
            { id: 2861, storyId: 149, category: "cause_effect", type: "multiple", question: "What caused Kai to realize the treasure was at Henderson Park?", options: ["The map spelled out the park's name", "He compared the map to satellite images and the three rivers matched three creeks", "His friend told him about the park", "He had found treasure there before"], correct: 1, hint: "How did Kai figure out where the map was leading him?", explanation: "Kai compared the map to satellite images and discovered the three rivers corresponded to three creeks meeting at Henderson Park!" },
            { id: 2862, storyId: 149, category: "compare_contrast", type: "multiple", question: "How does Kai's life BEFORE finding the map compare to AFTER?", options: ["He felt his life was ordinary, but after finding the map, magic entered his life", "He was already on an adventure before finding the map", "His life stayed exactly the same after finding the map", "He was happy before but sad after finding the map"], correct: 0, hint: "The passage mentions how Kai felt about his life before the map.", explanation: "Kai 'had always wished for adventure, for something magical in his ordinary life'--the map changed everything!" },
            { id: 2863, storyId: 149, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["The map was the most amazing thing Kai had ever seen", "The treasure is definitely worth millions of dollars", "Kai bought the map for fifty cents", "Henderson Park is the most magical place in town"], correct: 2, hint: "Which statement describes something that actually happened in the story?", explanation: "The passage directly states that Kai 'bought it for fifty cents'--this is a verifiable fact from the story!" },
            { id: 2864, storyId: 149, category: "author_purpose", type: "multiple", question: "Why did the author end the story with 'Kai knew exactly who to call'?", options: ["To wrap up the story with a complete ending", "To create suspense and make readers want to know what happens next", "To show that Kai is scared and needs help", "To explain how phone calls work"], correct: 1, hint: "How does this ending make you feel as a reader?", explanation: "The author creates a cliffhanger ending that leaves readers curious about who Kai will call and what happens next!" },
            { id: 2865, storyId: 149, category: "text_structure", type: "multiple", question: "How is 'The Whispering Woods' organized?", options: ["As a step-by-step guide to treasure hunting", "As a chronological adventure that builds mystery and excitement", "As a comparison between old maps and modern technology", "As a debate about whether magic is real"], correct: 1, hint: "Think about how the story moves from finding the map to discovering clues.", explanation: "The story follows a chronological structure, building mystery from finding the map to discovering where the treasure is hidden!" },
            { id: 2866, storyId: 149, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Kai unrolled the map on his desk.", answers: {"0": "noun", "1": "verb", "3": "noun", "6": "noun"}, hint: "Look for who does the action, what the action is, and the things mentioned.", explanation: "Kai is a noun (name), unrolled is a verb (action), map is a noun (thing), and desk is a noun (place/thing)!" },

// Story 150: Championship Decision (O) - Fiction
// IDs 2867-2878
            { id: 2867, storyId: 150, category: "theme", type: "multiple", question: "What is the main theme of 'Championship Decision'?", options: ["Winning championships is the most important thing in life", "True friendship and loyalty matter more than personal achievements", "Swimming is a difficult and demanding sport", "Parents should make decisions for their children"], correct: 1, hint: "Think about what Jordan chose to do and why.", explanation: "The story teaches that being there for someone you love is more important than winning a championship!" },
            { id: 2868, storyId: 150, category: "inference", type: "multiple", question: "What can you infer about why Jordan's mother said 'I can't decide for you'?", options: ["She didn't care about Jordan's swimming career", "She wanted Jordan to learn to make important moral decisions on her own", "She was too busy to help Jordan decide", "She thought Jordan should definitely go to the race"], correct: 1, hint: "Think about why a parent might not give their child the answer directly.", explanation: "Jordan's mother wanted her to develop her own values by making this difficult choice herself!" },
            { id: 2869, storyId: 150, category: "vocabulary", type: "multiple", question: "What does 'stable' mean when the passage says 'Aaliyah's mother was stable'?", options: ["She was standing up and walking around", "Her medical condition was no longer getting worse", "She was completely healed and ready to leave", "She was sitting in a stable with horses"], correct: 1, hint: "This word is used in a medical context about someone who had a heart attack.", explanation: "In a medical setting, 'stable' means a patient's condition has stopped getting worse and is now steady!" },
            { id: 2870, storyId: 150, category: "sequence", type: "multiple", question: "What is the correct order of events in this story?", options: ["Jordan gets a text, talks to her mom, drives to the hospital, stays all night", "Jordan drives to the hospital, gets a text, talks to her mom, swims the race", "Jordan swims the race, then visits Aaliyah at the hospital", "Jordan talks to the scouts, then drives to the hospital"], correct: 0, hint: "Follow the timeline from when Jordan gets the text message.", explanation: "Jordan first gets Aaliyah's text, then her mom helps her think, then she drives to the hospital and stays all night!" },
            { id: 2871, storyId: 150, category: "character", type: "multiple", question: "What does Jordan's decision reveal about her character?", options: ["She is selfish and only cares about herself", "She is compassionate and values people over personal success", "She is indecisive and can't make up her mind", "She doesn't really care about swimming"], correct: 1, hint: "Think about what Jordan gave up and why she did it.", explanation: "Jordan gave up a championship with university scouts watching because she valued her friendship with Aaliyah more!" },
            { id: 2872, storyId: 150, category: "main_idea", type: "multiple", question: "What is the main idea of 'Championship Decision'?", options: ["Jordan chooses to support her best friend over competing in a championship", "Jordan wins the state swimming championship", "Aaliyah's mother recovers from a heart attack", "Jordan gets a scholarship from university scouts"], correct: 0, hint: "What is the most important decision in the story?", explanation: "The story centers on Jordan's choice to be with Aaliyah at the hospital instead of swimming in the championship!" },
            { id: 2873, storyId: 150, category: "cause_effect", type: "multiple", question: "What caused Jordan to miss the state swimming championship?", options: ["She was injured during practice", "She was sick and couldn't swim", "She chose to go to the hospital to be with Aaliyah after her mom's heart attack", "The championship was cancelled due to weather"], correct: 2, hint: "Why did Jordan decide not to swim?", explanation: "Jordan chose to go to the hospital because her best friend Aaliyah needed her after Aaliyah's mother had a heart attack!" },
            { id: 2874, storyId: 150, category: "compare_contrast", type: "multiple", question: "What two things is Jordan weighing when she makes her decision?", options: ["Swimming practice vs. homework", "The championship and scholarship opportunities vs. being there for her friend", "Moving to a new city vs. staying at her current school", "Joining the swim team vs. joining the art club"], correct: 1, hint: "What could Jordan gain by racing, and what would she lose by not going to Aaliyah?", explanation: "Jordan weighs the championship, scouts, and scholarship against being there for Aaliyah when she needs her most!" },
            { id: 2875, storyId: 150, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Jordan was the best swimmer in the entire state", "Aaliyah's mother was the kindest person Jordan knew", "Jordan was ranked first in the 100-meter butterfly", "Going to the hospital was definitely the right decision"], correct: 2, hint: "Which statement can be verified from the text without personal judgment?", explanation: "The passage directly states Jordan 'was ranked first in the 100-meter butterfly'--this is a factual ranking!" },
            { id: 2876, storyId: 150, category: "author_purpose", type: "multiple", question: "Why did the author mention that Jordan had trained for three years and scouts were watching?", options: ["To show how much Jordan was sacrificing by choosing her friend", "To explain the rules of competitive swimming", "To make Jordan seem like a bad friend", "To promote university swimming programs"], correct: 0, hint: "How does knowing about the years of training affect how you view Jordan's choice?", explanation: "By emphasizing the stakes--three years of training and scouts watching--the author shows the enormous sacrifice Jordan made!" },
            { id: 2877, storyId: 150, category: "text_structure", type: "multiple", question: "How is 'Championship Decision' organized?", options: ["As a story building to a moral dilemma and its resolution", "As a step-by-step guide to competitive swimming", "As a comparison between two different swimmers", "As a flashback to Jordan's early swimming days"], correct: 0, hint: "Think about how the story sets up the conflict and shows Jordan making her choice.", explanation: "The story builds up the stakes (championship, scouts) then presents a moral dilemma that Jordan resolves by choosing friendship!" },
            { id: 2878, storyId: 150, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Jordan thought about the scouts, the scholarship opportunities, years of early morning practices.", answers: {"0": "noun", "1": "verb", "4": "noun", "7": "noun"}, hint: "Look for who does the action, what the action is, and the things being thought about.", explanation: "Jordan is a noun (name), thought is a verb (action), scouts is a noun (people), and scholarship is a noun (thing)!" },

// Story 151: Letters from 1957 (O) - Fiction
// IDs 2879-2890
            { id: 2879, storyId: 151, category: "theme", type: "multiple", question: "What is the main theme of 'Letters from 1957'?", options: ["Attics are great places to store old things", "Understanding the past helps us learn about injustice and the experiences of those who came before us", "Old letters are not worth reading", "Children should not look through their grandparents' belongings"], correct: 1, hint: "Think about what Harper learns from the letters and why Grandma Dorothy shares her story.", explanation: "The story teaches that understanding painful history helps us learn about injustice and the lives of people we love!" },
            { id: 2880, storyId: 151, category: "inference", type: "multiple", question: "Why did Grandma Dorothy say 'I thought I threw those away decades ago'?", options: ["She was happy Harper found the letters", "She had tried to hide this painful part of her past", "She didn't remember writing the letters", "She wanted Harper to read them"], correct: 1, hint: "Think about why someone might try to get rid of old love letters from a forbidden relationship.", explanation: "Dorothy had tried to destroy the letters because they represented a painful, forbidden love she had kept secret!" },
            { id: 2881, storyId: 151, category: "vocabulary", type: "multiple", question: "What does 'forbade' mean when the passage says 'a love that society forbade'?", options: ["Encouraged and supported", "Celebrated and honored", "Prohibited and did not allow", "Ignored and forgot about"], correct: 2, hint: "The passage says their relationship was illegal in 1950s Mississippi.", explanation: "'Forbade' means to prohibit or not allow--society did not permit relationships between Black and white people at that time!" },
            { id: 2882, storyId: 151, category: "sequence", type: "multiple", question: "What did Harper do AFTER reading the letters?", options: ["She put them back in the attic and forgot about them", "She went downstairs and asked Grandma Dorothy about Robert", "She called Robert on the phone", "She threw the letters away"], correct: 1, hint: "What did Harper do once she finished reading?", explanation: "After reading the letters, Harper went downstairs to Grandma Dorothy and asked her who Robert was!" },
            { id: 2883, storyId: 151, category: "character", type: "multiple", question: "What does Harper's reaction to the letters show about her?", options: ["She is uninterested in history", "She is empathetic and wants to understand her grandmother's past", "She is nosy and likes to gossip", "She is angry at her grandmother for keeping secrets"], correct: 1, hint: "How does Harper feel as she reads the letters, and what does she do afterward?", explanation: "Harper's 'heart ached' reading the letters and she approached her grandmother gently, showing empathy and care!" },
            { id: 2884, storyId: 151, category: "main_idea", type: "multiple", question: "What is the main idea of 'Letters from 1957'?", options: ["Harper discovers hidden letters revealing her grandmother's forbidden love during the era of racial segregation", "Harper organizes her grandmother's attic", "Grandma Dorothy collects antique letters", "Harper learns calligraphy from old letters"], correct: 0, hint: "What is the most significant discovery Harper makes?", explanation: "The story centers on Harper discovering letters that reveal her grandmother's secret love story set against racial injustice!" },
            { id: 2885, storyId: 151, category: "cause_effect", type: "multiple", question: "What caused Robert to be sent away to his uncle in the North?", options: ["Robert wanted to go to a better school up north", "Dorothy's father found out about their relationship", "Robert got a new job in another state", "Robert's family moved for better weather"], correct: 1, hint: "Robert's final letter gives the reason for his departure.", explanation: "Robert wrote 'Your father found out'--Dorothy's father discovered their relationship and had Robert sent away!" },
            { id: 2886, storyId: 151, category: "compare_contrast", type: "multiple", question: "How do Harper's feelings about the letters contrast with Grandma Dorothy's feelings?", options: ["Both are excited and happy about the discovery", "Harper is curious and empathetic while Dorothy is emotional and surprised they still exist", "Harper is angry while Dorothy is relieved", "Both want to throw the letters away"], correct: 1, hint: "Compare how Harper approaches Dorothy with the letters versus Dorothy's reaction.", explanation: "Harper is curious and gentle in her approach, while Dorothy is shocked and tearful that the letters still exist!" },
            { id: 2887, storyId: 151, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Robert was the bravest man in Mississippi", "The letters were the saddest things ever written", "The envelopes were dated 1957", "Dorothy should have told Harper about Robert sooner"], correct: 2, hint: "Which statement can be verified directly from the text?", explanation: "The passage directly states the letters were 'dated 1957'--this is a verifiable fact from the story!" },
            { id: 2888, storyId: 151, category: "author_purpose", type: "multiple", question: "Why did the author set this story in 1950s Mississippi?", options: ["To show a time and place where racial segregation laws made interracial love illegal", "Because Mississippi has the best attics for finding old letters", "To promote tourism in Mississippi", "Because all love stories take place in Mississippi"], correct: 0, hint: "The passage mentions that relationships between Black and white people were illegal at that time.", explanation: "The 1950s Mississippi setting is essential because it was a real time and place where such relationships were illegal!" },
            { id: 2889, storyId: 151, category: "text_structure", type: "multiple", question: "How is 'Letters from 1957' organized?", options: ["As a discovery narrative moving from present to past and back to present", "As a list of events in Robert's life", "As a comparison between the 1950s and today", "As a persuasive argument about civil rights"], correct: 0, hint: "Think about how the story moves between time periods.", explanation: "The story starts in the present (Harper finding letters), goes to the past (reading about 1957), and returns to the present (talking to Dorothy)!" },
            { id: 2890, storyId: 151, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Harper discovered a bundle of letters tied with faded ribbon.", answers: {"0": "noun", "1": "verb", "3": "noun", "7": "adjective", "8": "noun"}, hint: "Look for who does the action, what the action is, the things, and what describes a thing.", explanation: "Harper is a noun (name), discovered is a verb (action), bundle is a noun (thing), faded is an adjective (describes ribbon), and ribbon is a noun (thing)!" },

// Story 152: Nature's Living Lights (O) - Nonfiction
// IDs 2891-2902
            { id: 2891, storyId: 152, category: "theme", type: "multiple", question: "What is the main theme of 'Nature's Living Lights'?", options: ["Bioluminescence is a remarkable natural ability with important scientific applications", "The ocean is too dark for any life to survive", "Light bulbs are better than natural light", "Scientists should stop studying the ocean"], correct: 0, hint: "Think about what the passage explains about bioluminescence and why it matters.", explanation: "The passage highlights how bioluminescence is an amazing natural ability that scientists are studying for human benefits!" },
            { id: 2892, storyId: 152, category: "inference", type: "multiple", question: "Why is the deep-sea dragonfish's red light described as 'invisible night vision'?", options: ["The dragonfish can't actually see its own light", "Most deep-sea animals cannot see red light, so the dragonfish can see them without being detected", "Red light doesn't work underwater", "The dragonfish is actually blind"], correct: 1, hint: "Think about what advantage the dragonfish has if other animals can't see red light.", explanation: "Since most deep-sea animals cannot see red light, the dragonfish can illuminate and see prey without being noticed!" },
            { id: 2893, storyId: 152, category: "vocabulary", type: "multiple", question: "What does 'efficient' mean when the passage says bioluminescent light is 'incredibly efficient'?", options: ["Very bright and blinding", "Producing light with very little wasted energy", "Extremely expensive to produce", "Only lasting for a short time"], correct: 1, hint: "The passage compares bioluminescent light to light bulbs that waste energy as heat.", explanation: "'Efficient' means producing results with little waste--bioluminescent light creates light without wasting energy as heat!" },
            { id: 2894, storyId: 152, category: "sequence", type: "multiple", question: "According to the passage, what is the correct order of the bioluminescence chemical process?", options: ["Luciferin and luciferase combine with oxygen to create light", "Light creates oxygen that produces luciferin", "Oxygen breaks down luciferin to create heat", "Luciferase absorbs sunlight and stores it"], correct: 0, hint: "Look for the two substances and what they combine with.", explanation: "The passage states that luciferin and luciferase combine with oxygen to create light without heat!" },
            { id: 2895, storyId: 152, category: "character", type: "multiple", question: "What perspective do the scientists in this passage represent?", options: ["They are fearful of deep-sea creatures", "They are curious researchers finding practical uses for bioluminescence", "They believe bioluminescence is unimportant", "They only study bioluminescence for entertainment"], correct: 1, hint: "Think about what scientists are doing with their knowledge of bioluminescence.", explanation: "Scientists are shown as curious researchers applying bioluminescence to medicine, lighting, and ecosystem exploration!" },
            { id: 2896, storyId: 152, category: "main_idea", type: "multiple", question: "What is the main idea of 'Nature's Living Lights'?", options: ["Light bulbs waste too much energy", "Deep-sea creatures use bioluminescence for survival, and scientists are finding human applications for it", "The ocean is completely dark below the surface", "Jellyfish are the only animals that glow"], correct: 1, hint: "What are the two big points the passage makes about bioluminescence?", explanation: "The passage explains how animals use bioluminescence to survive AND how scientists are applying it for human benefit!" },
            { id: 2897, storyId: 152, category: "cause_effect", type: "multiple", question: "Why do some jellyfish release glowing clouds?", options: ["To attract mates", "To confuse predators while escaping", "To light their way in the dark ocean", "To communicate with other jellyfish"], correct: 1, hint: "Think about what problem the jellyfish is trying to solve.", explanation: "Jellyfish release glowing clouds to confuse predators, giving themselves time to escape!" },
            { id: 2898, storyId: 152, category: "compare_contrast", type: "multiple", question: "How does bioluminescent light compare to light from light bulbs?", options: ["Both waste the same amount of energy", "Bioluminescent light creates light without heat, while light bulbs waste energy as heat", "Light bulbs are more efficient than bioluminescence", "Bioluminescence produces more heat than light bulbs"], correct: 1, hint: "The passage directly compares these two types of light.", explanation: "The passage states that bioluminescent light is efficient because it creates light without heat, unlike wasteful light bulbs!" },
            { id: 2899, storyId: 152, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Bioluminescence is the most beautiful phenomenon in nature", "Deep-sea creatures are the most interesting animals on Earth", "Scientists estimate that ninety percent of deep-sea animals can produce light", "The dragonfish is the coolest animal in the ocean"], correct: 2, hint: "Which statement uses specific data from the passage?", explanation: "The passage states that 'scientists estimate that ninety percent of deep-sea animals can produce light'--a verifiable fact!" },
            { id: 2900, storyId: 152, category: "author_purpose", type: "multiple", question: "Why did the author describe specific animals like anglerfish, firefly squid, and dragonfish?", options: ["To give concrete examples of how different animals use bioluminescence", "To argue that these are the only animals with bioluminescence", "To scare readers about dangerous ocean creatures", "To explain why people should not go deep-sea diving"], correct: 0, hint: "How do these examples help the reader understand bioluminescence?", explanation: "The author uses specific animal examples to show the variety of ways creatures use bioluminescence for different purposes!" },
            { id: 2901, storyId: 152, category: "text_structure", type: "multiple", question: "How is 'Nature's Living Lights' organized?", options: ["As a chronological history of bioluminescence discoveries", "By explaining what bioluminescence is, how animals use it, and how humans apply it", "As a comparison between land and sea animals", "As a persuasive argument to protect the ocean"], correct: 1, hint: "Think about the three main sections of the passage.", explanation: "The passage moves from explaining what bioluminescence is, to animal uses, to human scientific applications!" },
            { id: 2902, storyId: 152, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Anglerfish dangle glowing lures to attract prey.", answers: {"0": "noun", "1": "verb", "2": "adjective", "3": "noun"}, hint: "Look for the animal, what it does, what describes the lures, and the things mentioned.", explanation: "Anglerfish is a noun (animal), dangle is a verb (action), glowing is an adjective (describes lures), and lures is a noun (things)!" },

// Story 153: How Video Games Are Made (O) - Nonfiction
// IDs 2903-2914
            { id: 2903, storyId: 153, category: "theme", type: "multiple", question: "What is the main theme of 'How Video Games Are Made'?", options: ["Playing video games is easy and fun", "Creating video games is a complex, collaborative process involving many professionals over years", "Programming is the only important part of game development", "Video games are a waste of time"], correct: 1, hint: "Think about how many people and steps are involved in making a game.", explanation: "The passage emphasizes that game development requires hundreds of creative professionals working together for years!" },
            { id: 2904, storyId: 153, category: "inference", type: "multiple", question: "Why are many games abandoned during the prototyping stage?", options: ["The programmers get bored with the project", "Testing reveals that the game mechanics don't work well or aren't fun", "The company runs out of paper for design documents", "Players don't buy the prototypes"], correct: 1, hint: "The passage says games are abandoned when 'testing reveals problems.'", explanation: "Prototyping tests core mechanics like jumping and difficulty balance--if these don't work, the game isn't worth continuing!" },
            { id: 2905, storyId: 153, category: "vocabulary", type: "multiple", question: "What does 'fundamental' mean when the passage says designers ask 'fundamental questions'?", options: ["Unimportant and minor", "Basic and essential", "Confusing and complicated", "Funny and entertaining"], correct: 1, hint: "These are the first and most important questions designers ask.", explanation: "'Fundamental' means basic and essential--these are the core questions that everything else builds upon!" },
            { id: 2906, storyId: 153, category: "sequence", type: "multiple", question: "What is the correct order of game development phases described in the passage?", options: ["Concept phase, prototyping, full production, quality assurance, marketing and launch", "Marketing, prototyping, concept phase, launch", "Full production, concept phase, quality assurance, prototyping", "Quality assurance, marketing, full production, concept phase"], correct: 0, hint: "Follow the order the passage describes each phase.", explanation: "The passage describes: concept phase first, then prototyping, full production, quality assurance, and finally marketing and launch!" },
            { id: 2907, storyId: 153, category: "character", type: "multiple", question: "What role do quality assurance testers play in game development?", options: ["They design the characters and environments", "They write the game's story and dialogue", "They play the game repeatedly to find bugs that need fixing", "They create the marketing trailers"], correct: 2, hint: "The passage mentions testers searching for something specific.", explanation: "Quality assurance testers play the game repeatedly to find bugs--a typical major game might have over 10,000 bugs to fix!" },
            { id: 2908, storyId: 153, category: "main_idea", type: "multiple", question: "What is the main idea of 'How Video Games Are Made'?", options: ["Video games take years and hundreds of professionals across many disciplines to create", "Programming is the only step in making video games", "Video games are made by a single person in a few weeks", "Marketing is the most important part of game development"], correct: 0, hint: "What does the passage emphasize about the game development process?", explanation: "The passage shows that games require years of work by hundreds of professionals including artists, writers, programmers, and testers!" },
            { id: 2909, storyId: 153, category: "cause_effect", type: "multiple", question: "What is the effect of sound designers crafting music for a game?", options: ["It makes the game file larger", "It enhances the emotional impact of the game experience", "It slows down the development process", "It replaces the need for visual effects"], correct: 1, hint: "The passage explains what good music does for a game.", explanation: "Sound designers craft music that 'enhances emotional impact,' making players feel more connected to the game experience!" },
            { id: 2910, storyId: 153, category: "compare_contrast", type: "multiple", question: "How does the time it takes to CREATE a game compare to the time players spend EXPERIENCING it?", options: ["Both take about the same amount of time", "Players experience in hours what took thousands of people years to create", "Creating a game takes less time than playing it", "Players spend years playing while developers spend hours making games"], correct: 1, hint: "Look at the last sentence of the passage.", explanation: "The passage states that 'players experience in hours what took thousands of people years to create'!" },
            { id: 2911, storyId: 153, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Video games are the best form of entertainment", "All video games should take at least five years to develop", "A typical major game might have over 10,000 bugs requiring fixes before release", "Programming is the most difficult part of game development"], correct: 2, hint: "Which statement uses a specific number from the passage?", explanation: "The passage states that 'a typical major game might have over 10,000 bugs requiring fixes'--a specific, verifiable claim!" },
            { id: 2912, storyId: 153, category: "author_purpose", type: "multiple", question: "Why did the author write 'How Video Games Are Made'?", options: ["To convince readers to stop playing video games", "To inform readers about the detailed process behind video game creation", "To argue that one game company is better than another", "To teach readers how to become programmers"], correct: 1, hint: "What does the reader learn by the end of the passage?", explanation: "The author's purpose is to inform readers about all the steps, people, and effort involved in creating video games!" },
            { id: 2913, storyId: 153, category: "text_structure", type: "multiple", question: "How is 'How Video Games Are Made' organized?", options: ["As a sequential process describing each phase of game development in order", "As a comparison between good and bad video games", "As a persuasive argument for more video game funding", "As a collection of random facts about gaming"], correct: 0, hint: "Notice how the passage moves through each development phase.", explanation: "The passage is organized sequentially, walking through each phase from concept to launch in order!" },
            { id: 2914, storyId: 153, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Programmers build simple versions to test core mechanics.", answers: {"0": "noun", "1": "verb", "2": "adjective", "3": "noun"}, hint: "Look for who does the action, what the action is, what describes the thing, and the things.", explanation: "Programmers is a noun (people), build is a verb (action), simple is an adjective (describes versions), and versions is a noun (things)!" },

// Story 154: When Weather Turns Deadly (O) - Nonfiction
// IDs 2915-2926
            { id: 2915, storyId: 154, category: "theme", type: "multiple", question: "What is the main theme of 'When Weather Turns Deadly'?", options: ["Weather is always predictable and safe", "Understanding deadly weather phenomena helps communities prepare and survive", "Hurricanes are the only dangerous type of weather", "People should never live near the ocean"], correct: 1, hint: "Think about why the author describes each disaster type and its survival strategies.", explanation: "The passage emphasizes that understanding these weather events helps communities prepare with the right survival strategies!" },
            { id: 2916, storyId: 154, category: "inference", type: "multiple", question: "Why might the calm eye of a hurricane create 'false safety'?", options: ["The eye actually has the strongest winds", "People might think the storm has passed when dangerous winds surround the calm center", "The eye is where lightning strikes most", "The eye causes flooding"], correct: 1, hint: "Think about what happens after the eye passes over an area.", explanation: "People might think the storm is over during the calm eye, but violent winds surround it and will return as the storm continues!" },
            { id: 2917, storyId: 154, category: "vocabulary", type: "multiple", question: "What does 'seismic' mean when the passage says 'warning systems now monitor seismic activity'?", options: ["Related to earthquakes and ground movement", "Related to ocean currents and tides", "Related to wind speed and direction", "Related to temperature and humidity"], correct: 0, hint: "The passage connects seismic activity to underwater earthquakes that cause tsunamis.", explanation: "'Seismic' means related to earthquakes--monitoring ground movement helps predict tsunamis caused by underwater earthquakes!" },
            { id: 2918, storyId: 154, category: "sequence", type: "multiple", question: "According to the passage, what happens to tsunami waves as they move from deep water to coastline?", options: ["They stay the same size throughout", "They appear small in deep water but grow into devastating walls near coastlines", "They start huge and get smaller near shore", "They disappear completely before reaching land"], correct: 1, hint: "The passage describes how tsunami waves change as they approach land.", explanation: "Tsunami waves 'appear small in deep water but grow into devastating walls near coastlines'!" },
            { id: 2919, storyId: 154, category: "character", type: "multiple", question: "What perspective does the author present about communities facing deadly weather?", options: ["Communities are helpless against all weather disasters", "Communities can prepare and protect themselves through understanding and technology", "Communities should simply move away from dangerous areas", "Communities don't need warning systems"], correct: 1, hint: "What solutions does the passage mention for each type of disaster?", explanation: "The author shows that satellite tracking, underground shelters, and warning systems all help communities prepare!" },
            { id: 2920, storyId: 154, category: "main_idea", type: "multiple", question: "What is the main idea of 'When Weather Turns Deadly'?", options: ["Hurricanes, tornadoes, and tsunamis are destructive forces, but understanding them helps people survive", "Tornadoes are the most dangerous type of weather", "Weather cannot be predicted or prepared for", "Climate change is not real"], correct: 0, hint: "What is the passage mainly about across all three disaster types?", explanation: "The passage explains how hurricanes, tornadoes, and tsunamis work and how understanding them helps people prepare and survive!" },
            { id: 2921, storyId: 154, category: "cause_effect", type: "multiple", question: "What causes tsunamis to form?", options: ["Strong winds blowing across the ocean surface", "Warm ocean water evaporating quickly", "Underwater earthquakes or volcanic eruptions", "The moon's gravitational pull on tides"], correct: 2, hint: "The passage describes what triggers tsunamis.", explanation: "Tsunamis 'originate from underwater earthquakes or volcanic eruptions' that displace ocean water!" },
            { id: 2922, storyId: 154, category: "compare_contrast", type: "multiple", question: "How do hurricanes and tornadoes differ according to the passage?", options: ["Hurricanes are small and tornadoes are massive", "Hurricanes form over land while tornadoes form over water", "Hurricanes are wide and last weeks, while tornadoes form rapidly and are tightly spinning", "Hurricanes are unpredictable while tornadoes give days of warning"], correct: 2, hint: "Compare the size, duration, and predictability of each.", explanation: "Hurricanes span 500 miles and last weeks with days of warning, while tornadoes form rapidly and unpredictably!" },
            { id: 2923, storyId: 154, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Hurricanes are scarier than tornadoes", "Hurricane Katrina was the worst disaster in history", "The 2004 Indian Ocean tsunami killed approximately 230,000 people across fourteen countries", "Tornadoes are the most unfair type of weather"], correct: 2, hint: "Which statement uses specific numbers from the passage?", explanation: "The passage states the 2004 tsunami 'killed approximately 230,000 people across fourteen countries'--a verifiable fact!" },
            { id: 2924, storyId: 154, category: "author_purpose", type: "multiple", question: "Why did the author include specific statistics about Hurricane Katrina and the Indian Ocean tsunami?", options: ["To make the passage longer", "To show the real-world devastation these events cause and why preparation matters", "To scare readers away from traveling", "To compare the United States and the Indian Ocean"], correct: 1, hint: "How do real numbers help readers understand the importance of preparation?", explanation: "Specific statistics about deaths and damage make the passage's message about preparation more urgent and real!" },
            { id: 2925, storyId: 154, category: "text_structure", type: "multiple", question: "How is 'When Weather Turns Deadly' organized?", options: ["As a chronological history of all weather events", "By describing three types of deadly weather, each with its characteristics and survival strategies", "As a persuasive argument to fund weather research", "As a personal story about surviving a hurricane"], correct: 1, hint: "Notice how the passage discusses each weather type separately.", explanation: "The passage is organized by topic--each section covers a different deadly weather type with its features and survival strategies!" },
            { id: 2926, storyId: 154, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Tornadoes are tightly spinning air columns descending from thunderstorms.", answers: {"0": "noun", "2": "adverb", "3": "verb", "5": "noun"}, hint: "Look for the subject, how it moves, the action, and the things described.", explanation: "Tornadoes is a noun (thing), tightly is an adverb (how they spin), spinning is a verb (action), and columns is a noun (thing)!" },

// Story 155: Secrets of the Pyramids (O) - Nonfiction
// IDs 2927-2938
            { id: 2927, storyId: 155, category: "theme", type: "multiple", question: "What is the main theme of 'Secrets of the Pyramids'?", options: ["Ancient Egypt was a boring civilization", "The pyramids remain one of history's greatest mysteries despite modern research and technology", "Scientists have completely solved how the pyramids were built", "The pyramids are not very impressive structures"], correct: 1, hint: "Think about what the passage says about unsolved mysteries.", explanation: "The passage emphasizes that despite decades of research, many mysteries about the pyramids remain unsolved!" },
            { id: 2928, storyId: 155, category: "inference", type: "multiple", question: "Why does the author say the pyramids' precision 'seems impossible without lasers or computers'?", options: ["Ancient Egyptians actually had lasers", "The incredible accuracy of the construction is hard to explain with ancient tools alone", "Modern builders could not replicate the pyramids", "Lasers were invented in ancient Egypt"], correct: 1, hint: "Think about the level of precision described and what tools were available then.", explanation: "The near-perfect leveling and alignment achieved with ancient tools is so impressive it seems to require modern technology!" },
            { id: 2929, storyId: 155, category: "vocabulary", type: "multiple", question: "What does 'cardinal' mean when the passage says the sides 'align almost exactly with cardinal directions'?", options: ["Related to the red bird called a cardinal", "The four main compass directions: north, south, east, and west", "Related to Catholic Church leaders", "Random or unimportant directions"], correct: 1, hint: "Think about the main directions on a compass.", explanation: "'Cardinal directions' are the four main compass points--north, south, east, and west--and the pyramid aligns precisely with them!" },
            { id: 2930, storyId: 155, category: "sequence", type: "multiple", question: "According to the most accepted theory, how were the stone blocks moved?", options: ["They were carried by elephants to the construction site", "Workers dragged stones up ramps using wooden sledges and water to reduce friction", "They were floated through underground rivers", "Aliens transported them using advanced technology"], correct: 1, hint: "The passage describes what most archaeologists believe about how stones were moved.", explanation: "Most archaeologists believe workers dragged stones up massive ramps using wooden sledges and water to reduce friction!" },
            { id: 2931, storyId: 155, category: "character", type: "multiple", question: "What perspective do archaeologists bring to studying the pyramids?", options: ["They believe the pyramids are not worth studying", "They use evidence and new discoveries to build theories about pyramid construction", "They have given up trying to explain how the pyramids were built", "They only study the outside of the pyramids"], correct: 1, hint: "Think about how the passage describes archaeologists' approach and recent discoveries.", explanation: "Archaeologists use evidence like the 2013 papyrus discovery and cosmic ray scanning to build and test theories!" },
            { id: 2932, storyId: 155, category: "main_idea", type: "multiple", question: "What is the main idea of 'Secrets of the Pyramids'?", options: ["The Great Pyramid's incredible construction and remaining mysteries continue to puzzle researchers", "The pyramids were easy to build with ancient tools", "All mysteries about the pyramids have been solved", "The pyramids are located in the desert"], correct: 0, hint: "What is the passage mainly about?", explanation: "The passage focuses on the amazing statistics of pyramid construction and the mysteries that still remain unsolved!" },
            { id: 2933, storyId: 155, category: "cause_effect", type: "multiple", question: "What has caused hidden chambers in the pyramid to be discovered recently?", options: ["Workers accidentally broke through a wall", "Cosmic ray scanning technology revealed them", "Tourists found a secret entrance", "Archaeologists read about them in ancient texts"], correct: 1, hint: "The passage mentions a modern technology used to find hidden spaces.", explanation: "Hidden chambers were discovered through cosmic ray scanning, a modern technology that can see inside solid structures!" },
            { id: 2934, storyId: 155, category: "compare_contrast", type: "multiple", question: "How does the passage contrast ancient Egyptian tools with the precision they achieved?", options: ["Ancient tools were highly advanced and easily explain the precision", "The passage doesn't mention any contrast", "The precision seems impossible without modern technology, yet they achieved it with ancient methods", "Modern tools produce less precise results than ancient ones"], correct: 2, hint: "Think about the near-perfect leveling and alignment described.", explanation: "The passage contrasts the lack of modern technology with incredibly precise results like 2.1 cm variation across 13 acres!" },
            { id: 2935, storyId: 155, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["The pyramids are the most beautiful structures ever built", "Ancient Egyptians were smarter than modern engineers", "The Great Pyramid contains approximately 2.3 million stone blocks", "The pyramids will never be fully understood"], correct: 2, hint: "Which statement uses a specific number that can be verified?", explanation: "The passage states the Great Pyramid 'contains approximately 2.3 million stone blocks'--a specific, verifiable fact!" },
            { id: 2936, storyId: 155, category: "author_purpose", type: "multiple", question: "Why did the author include the detail about the 2013 papyrus document?", options: ["To show that new evidence continues to be discovered about the pyramids", "To prove that ancient Egyptians could write", "To explain how paper was invented", "To show that boats existed in ancient times"], correct: 0, hint: "How does this recent discovery relate to the passage's theme of ongoing mystery?", explanation: "The 2013 papyrus shows that even after 4,500 years, new evidence about pyramid construction is still being found!" },
            { id: 2937, storyId: 155, category: "text_structure", type: "multiple", question: "How is 'Secrets of the Pyramids' organized?", options: ["As a step-by-step guide to building a pyramid", "By presenting the amazing statistics, then construction theories, then remaining mysteries", "As a chronological history of ancient Egypt", "As a debate between scientists who disagree"], correct: 1, hint: "Notice how the passage moves from facts to theories to unsolved questions.", explanation: "The passage is organized from impressive statistics, to construction theories, to mysteries that remain unsolved!" },
            { id: 2938, storyId: 155, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Workers dragged stones up massive ramps using wooden sledges.", answers: {"0": "noun", "1": "verb", "2": "noun", "4": "adjective", "5": "noun"}, hint: "Look for who does the action, the action itself, the objects, and what describes them.", explanation: "Workers is a noun (people), dragged is a verb (action), stones is a noun (things), massive is an adjective (describes ramps), and ramps is a noun (things)!" },

// Story 156: The Making of an Olympian (O) - Nonfiction
// IDs 2939-2950
            { id: 2939, storyId: 156, category: "theme", type: "multiple", question: "What is the main theme of 'The Making of an Olympian'?", options: ["Anyone can easily become an Olympic athlete", "Becoming an Olympian requires extraordinary dedication, sacrifice, and support over many years", "Only naturally talented people can become athletes", "Olympic athletes don't need coaches or trainers"], correct: 1, hint: "Think about everything the passage says athletes must invest.", explanation: "The passage shows that becoming an Olympian takes a decade or more of intense training, sacrifice, and support from many people!" },
            { id: 2940, storyId: 156, category: "inference", type: "multiple", question: "Why do gymnasts, swimmers, and figure skaters start training earlier than athletes in other sports?", options: ["These sports are easier than others", "Their sports reward skills developed before puberty", "These athletes are naturally more talented", "These sports don't require much practice"], correct: 1, hint: "The passage gives a specific reason related to physical development.", explanation: "The passage states these sports 'reward skills developed before puberty,' so athletes must start training very young!" },
            { id: 2941, storyId: 156, category: "vocabulary", type: "multiple", question: "What does 'protocols' mean when the passage mentions 'recovery protocols'?", options: ["Types of sports equipment", "Established procedures and routines", "Athletic competitions", "Dietary supplements"], correct: 1, hint: "The passage lists cryotherapy, massage, and monitored rest as examples.", explanation: "'Protocols' means established procedures or routines--recovery protocols are the specific methods athletes use to heal and rest!" },
            { id: 2942, storyId: 156, category: "sequence", type: "multiple", question: "According to the passage, what is the typical progression of an Olympic athlete's career?", options: ["Start specialized training around age 6-7, train 20-30 hours weekly by age 12, spend a decade or more preparing", "Start training at age 16, compete within a year", "Begin with mental training, then physical training", "Train for one year, then try out for the Olympics"], correct: 0, hint: "Follow the ages and milestones mentioned in the passage.", explanation: "Athletes begin specialized training by age 6-7, train 20-30 hours weekly by age 12, over a journey spanning a decade or more!" },
            { id: 2943, storyId: 156, category: "character", type: "multiple", question: "What do sports psychologists help Olympic athletes develop?", options: ["Better physical strength and speed", "Mental toughness, visualization techniques, and strategies for handling pressure", "Cooking skills for proper nutrition", "Social media presence and fame"], correct: 1, hint: "The passage specifically lists what sports psychologists help with.", explanation: "Sports psychologists help athletes develop 'mental toughness, visualization techniques, and strategies for handling pressure'!" },
            { id: 2944, storyId: 156, category: "main_idea", type: "multiple", question: "What is the main idea of 'The Making of an Olympian'?", options: ["The journey to becoming an Olympic athlete is incredibly demanding, requiring years of training, money, and sacrifice", "Olympic athletes are born with natural talent and don't need to train", "Injuries never happen to Olympic athletes", "Only wealthy families can produce Olympic athletes"], correct: 0, hint: "What does the passage emphasize about the overall Olympic journey?", explanation: "The passage shows the enormous demands of the Olympic journey: years of intense training, huge costs, and constant injury risk!" },
            { id: 2945, storyId: 156, category: "cause_effect", type: "multiple", question: "What is one effect of training 20 to 30 hours weekly by age twelve?", options: ["Athletes become famous immediately", "It affects education, friendships, and family relationships", "Athletes earn large salaries", "It guarantees a spot on the Olympic team"], correct: 1, hint: "The passage mentions what intensive training schedules affect.", explanation: "The passage states that 'this intensive schedule affects education, friendships, and family relationships'!" },
            { id: 2946, storyId: 156, category: "compare_contrast", type: "multiple", question: "How does the passage contrast the physical and mental aspects of Olympic training?", options: ["Physical training is the only part that matters", "Physical training is described alongside essential mental preparation by sports psychologists", "Mental training is more important than physical training", "Physical and mental training are completely separate and unrelated"], correct: 1, hint: "The passage says physical training is 'only part of the equation.'", explanation: "The passage states that physical training is 'only part of the equation' and emphasizes mental preparation is equally important!" },
            { id: 2947, storyId: 156, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Olympic athletes have the hardest jobs in the world", "Olympic training is the most rewarding experience possible", "Olympic training can cost families $50,000 to $100,000 annually", "Every young athlete should try to become an Olympian"], correct: 2, hint: "Which statement provides a specific, verifiable number?", explanation: "The passage states that 'Olympic training can cost families $50,000 to $100,000 annually'--a specific financial fact!" },
            { id: 2948, storyId: 156, category: "author_purpose", type: "multiple", question: "Why did the author include the detail about 'one wrong landing, one torn ligament'?", options: ["To discourage young athletes from trying sports", "To show how fragile an Olympic dream can be despite years of preparation", "To explain how ligaments work in the human body", "To promote injury prevention products"], correct: 1, hint: "What point is the author making about the risks athletes face?", explanation: "The author shows that years of preparation can be ended by a single injury, highlighting how fragile the Olympic dream is!" },
            { id: 2949, storyId: 156, category: "text_structure", type: "multiple", question: "How is 'The Making of an Olympian' organized?", options: ["As a biography of one specific Olympic athlete", "By covering different aspects of Olympic preparation: physical training, mental preparation, finances, and injury risk", "As a debate about whether the Olympics should continue", "In chronological order of Olympic Games history"], correct: 1, hint: "Notice how each section covers a different aspect of the Olympic journey.", explanation: "The passage is organized by topic--physical training, mental preparation, financial costs, and injury risks!" },
            { id: 2950, storyId: 156, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Coaches analyze video footage frame by frame, seeking tiny improvements.", answers: {"0": "noun", "1": "verb", "2": "adjective", "3": "noun"}, hint: "Look for who does the action, the action itself, what describes the thing, and the thing.", explanation: "Coaches is a noun (people), analyze is a verb (action), video is an adjective (describes footage), and footage is a noun (thing)!" },

// Story 157: Food Deserts in America (O) - Nonfiction
// IDs 2951-2962
            { id: 2951, storyId: 157, category: "theme", type: "multiple", question: "What is the main theme of 'Food Deserts in America'?", options: ["Fast food restaurants are always unhealthy", "Millions of Americans lack access to healthy food due to systemic inequality, with serious health consequences", "Grocery stores are too expensive for everyone", "People in food deserts choose not to eat healthy food"], correct: 1, hint: "Think about why food deserts exist and what effect they have.", explanation: "The passage shows that food deserts result from systemic inequality and cause serious health problems for millions of Americans!" },
            { id: 2952, storyId: 157, category: "inference", type: "multiple", question: "Why do food deserts concentrate in low-income and predominantly minority neighborhoods?", options: ["People in these areas prefer fast food over grocery stores", "These neighborhoods have no available land for stores", "Decades of discriminatory business practices caused supermarket chains to avoid these areas", "The weather in these areas makes it hard to grow food"], correct: 2, hint: "The passage explains historical reasons for why supermarkets avoided certain areas.", explanation: "The passage states food deserts reflect 'decades of discriminatory business practices' where chains avoided low-profit areas!" },
            { id: 2953, storyId: 157, category: "vocabulary", type: "multiple", question: "What does 'discriminatory' mean when the passage says 'decades of discriminatory business practices'?", options: ["Fair and equal treatment of all people", "Smart and profitable business decisions", "Unfairly treating certain groups of people differently", "Random and unpredictable choices"], correct: 2, hint: "The passage connects this word to why certain neighborhoods were avoided by businesses.", explanation: "'Discriminatory' means unfairly treating people differently based on characteristics like race or income!" },
            { id: 2954, storyId: 157, category: "sequence", type: "multiple", question: "According to the passage, what is the chain of events from food deserts to health problems?", options: ["Residents lack access to grocery stores, rely on fast food, then develop higher rates of obesity, diabetes, and heart disease", "Residents choose fast food, grocery stores leave, then health improves", "Health problems cause grocery stores to close, creating food deserts", "Fast food restaurants open, health improves, then grocery stores leave"], correct: 0, hint: "Follow the cause-and-effect chain described in the passage.", explanation: "Without grocery access, residents rely on convenience stores and fast food, leading to obesity, diabetes, and heart disease!" },
            { id: 2955, storyId: 157, category: "character", type: "multiple", question: "What perspective does the author present about people living in food deserts?", options: ["They are responsible for their own poor eating habits", "They are victims of systemic problems beyond their control who deserve better access", "They don't want healthy food options", "They should simply move to areas with better grocery stores"], correct: 1, hint: "Think about whether the author blames individuals or systems.", explanation: "The author presents food desert residents as affected by systemic issues like discriminatory business practices, not personal choices!" },
            { id: 2956, storyId: 157, category: "main_idea", type: "multiple", question: "What is the main idea of 'Food Deserts in America'?", options: ["Food deserts affect millions of Americans, causing health problems due to lack of access to healthy food", "Everyone in America has equal access to healthy food", "Fast food is the main cause of all health problems", "Grocery stores are not important for communities"], correct: 0, hint: "What is the passage mainly about?", explanation: "The passage explains what food deserts are, how they affect health, why they exist, and what solutions are being tried!" },
            { id: 2957, storyId: 157, category: "cause_effect", type: "multiple", question: "What caused supermarket chains to historically avoid low-income areas?", options: ["There were no buildings available for stores", "The roads were too narrow for delivery trucks", "The chains cited lower profits as the reason", "Government regulations prevented them from opening stores there"], correct: 2, hint: "The passage explains the business reason chains gave for avoiding these areas.", explanation: "Supermarket chains 'historically avoided these areas, citing lower profits'!" },
            { id: 2958, storyId: 157, category: "compare_contrast", type: "multiple", question: "How does the passage contrast food deserts with other neighborhoods?", options: ["Food deserts have grocery stores on every corner while other areas don't", "In food deserts, fast food is nearby but grocery stores are miles away, unlike other neighborhoods", "There is no difference between food deserts and other neighborhoods", "Other neighborhoods have more fast food restaurants than food deserts"], correct: 1, hint: "Think about the opening description of what a food desert looks like.", explanation: "The passage opens by contrasting neighborhoods where the nearest grocery is ten miles away but fast food lines every block!" },
            { id: 2959, storyId: 157, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Food deserts are the worst problem facing America today", "Everyone should eat organic food from grocery stores", "Approximately 39 million Americans live in food deserts", "Community gardens are the best solution to food deserts"], correct: 2, hint: "Which statement provides a specific, verifiable number?", explanation: "The passage states 'approximately 39 million Americans live in food deserts'--a specific statistic that can be verified!" },
            { id: 2960, storyId: 157, category: "author_purpose", type: "multiple", question: "Why did the author begin the passage with 'Imagine living where the nearest grocery store is ten miles away'?", options: ["To help readers personally connect with the experience of living in a food desert", "To explain the rules of grocery store placement", "To argue that grocery stores should be closer together", "To compare urban and rural transportation"], correct: 0, hint: "How does asking readers to 'imagine' change how they connect with the topic?", explanation: "By asking readers to imagine the experience, the author helps them empathize with people living in food deserts!" },
            { id: 2961, storyId: 157, category: "text_structure", type: "multiple", question: "How is 'Food Deserts in America' organized?", options: ["As a personal story about someone living in a food desert", "By defining the problem, describing health effects, explaining causes, and presenting solutions", "As a comparison between urban and rural grocery stores", "In chronological order of when food deserts developed"], correct: 1, hint: "Notice how the passage moves from definition to effects to causes to solutions.", explanation: "The passage follows a logical structure: define food deserts, show health effects, explain causes, and describe solutions!" },
            { id: 2962, storyId: 157, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Community gardens provide locally grown food while building connections.", answers: {"0": "adjective", "1": "noun", "2": "verb", "3": "adverb", "4": "adjective"}, hint: "Look for what describes the noun, the noun itself, the action, and how/what type.", explanation: "Community is an adjective (describes gardens), gardens is a noun (thing), provide is a verb (action), locally is an adverb (how it's grown), and grown is an adjective (describes food)!" },
