// Level O Questions (storyIds 147-157) - Real, story-specific comprehension questions

// Story 147: River Rapids (O) - Fiction
// IDs 2831-2842
            { id: 2831, storyId: 147, category: "theme", type: "multiple", question: "What is the main theme of 'River Rapids'?", options: ["Working together and trusting each other to overcome challenges", "The importance of wearing life jackets while canoeing", "Learning to swim in rough water", "Why rivers are dangerous places to visit"], correct: 0, hint: "Think about how Marcus and Destiny got through the rapids.", explanation: "The story shows that teamwork and trust helped Marcus and Destiny survive the dangerous rapids!" },
            { id: 2832, storyId: 147, category: "inference", type: "multiple", question: "Why were Marcus and Destiny able to paddle 'in perfect synchronization'?", options: ["They were professional river guides", "They had never been in a canoe before", "They had practiced together for months", "Their instructor was paddling with them"], correct: 2, hint: "The story mentions something about their practice.", explanation: "The text says 'their months of practice finally paying off,' showing they had trained together!" },
            { id: 2833, storyId: 147, category: "vocabulary", type: "multiple", question: "What does 'lurched' mean when the passage says 'The canoe lurched violently'?", options: ["Floated gently downstream", "Moved suddenly and unsteadily", "Sank slowly underwater", "Spun in a complete circle"], correct: 1, hint: "Think about what happens when you hit unexpected rapids.", explanation: "'Lurched' means to make a sudden, unsteady movement, like when the canoe hit the rapids!" },
            { id: 2834, storyId: 147, category: "sequence", type: "multiple", question: "What happened AFTER Marcus steered the canoe hard right to avoid the boulder?", options: ["They immediately reached calm water", "Marcus remembered his instructor's words", "Destiny spotted where the river narrowed between canyon walls", "They capsized in the water"], correct: 2, hint: "The boulder was the first obstacle, but there were more ahead.", explanation: "After avoiding the boulder, Destiny pointed out that the river narrowed between canyon walls ahead!" },
            { id: 2835, storyId: 147, category: "character", type: "multiple", question: "What character trait does Marcus show when he makes a 'split-second decision' to steer right?", options: ["He is indecisive and unsure", "He is quick-thinking and decisive under pressure", "He is reckless and careless", "He is frightened and panicking"], correct: 1, hint: "Think about how Marcus reacts in the moment of danger.", explanation: "Marcus shows he can think and act quickly under pressure, making a fast decision that saves them!" },
            { id: 2836, storyId: 147, category: "main_idea", type: "multiple", question: "What is the main idea of 'River Rapids'?", options: ["Marcus and Destiny use teamwork and skill to navigate dangerous rapids together", "Canoeing is a popular outdoor sport for siblings", "Rivers can change from calm to dangerous without warning", "Marcus learns how to steer a canoe for the first time"], correct: 0, hint: "What is the most important thing that happens in this story?", explanation: "The story is mainly about how Marcus and Destiny work together to safely navigate through the rapids!" },
            { id: 2837, storyId: 147, category: "cause_effect", type: "multiple", question: "What caused Marcus to look for a V-shape pointing downstream?", options: ["Destiny told him to look for one", "He saw a sign posted on the canyon wall", "He remembered his kayaking instructor's advice", "He read about it in a book that morning"], correct: 2, hint: "Where did Marcus learn about reading the water?", explanation: "Marcus remembered his instructor's words: 'Look for V-shapes pointing downstream--that's your safe path!'" },
            { id: 2838, storyId: 147, category: "compare_contrast", type: "multiple", question: "How is the beginning of the canoe trip different from the middle?", options: ["It starts on a lake and moves to a river", "It starts peaceful and becomes dangerous", "It starts at night and becomes daytime", "It starts with three people and ends with two"], correct: 1, hint: "Think about how the passage describes the afternoon before the rapids.", explanation: "The story contrasts their 'peaceful afternoon' with the sudden dangerous rapids they encounter!" },
            { id: 2839, storyId: 147, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Canoeing is the most exciting water sport", "The rapids were the scariest thing Marcus had ever seen", "Water splashed over the sides, soaking their supplies", "Destiny was the best paddler on the river"], correct: 2, hint: "Which statement describes something that actually happened without adding personal judgment?", explanation: "The passage directly states that water splashed over the sides and soaked their supplies!" },
            { id: 2840, storyId: 147, category: "author_purpose", type: "multiple", question: "Why did the author include the detail about Marcus remembering his kayaking instructor?", options: ["To show that past learning can help in real emergencies", "To advertise kayaking classes", "To explain why Marcus doesn't like kayaking", "To show that Marcus has a bad memory"], correct: 0, hint: "How does remembering the instructor help Marcus in this moment?", explanation: "The author shows that what Marcus learned in training directly helped him find the safe path through the rapids!" },
            { id: 2841, storyId: 147, category: "text_structure", type: "multiple", question: "How is 'River Rapids' organized?", options: ["As a chronological action sequence with rising tension and resolution", "As a comparison between canoeing and kayaking", "As a list of safety rules for river travel", "As a flashback to a past adventure"], correct: 0, hint: "Think about how the events build from calm to dangerous to safe again.", explanation: "The story follows a timeline with rising action (hitting rapids, avoiding obstacles) leading to resolution (reaching calm water)!" },
            { id: 2842, storyId: 147, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Marcus made a split-second decision, steering hard right.", answers: {"0": "noun", "1": "verb", "3": "adjective", "4": "noun"}, hint: "Look for who does the action, what the action is, and what describes the noun.", explanation: "Marcus is a noun (name), made is a verb (action), split-second is an adjective (describes decision), and decision is a noun (thing)!" },

// Story 148: The New Kid's Secret (O) - Fiction
// IDs 2843-2854
            { id: 2843, storyId: 148, category: "theme", type: "multiple", question: "What is the main theme of 'The New Kid's Secret'?", options: ["School cafeterias should have better food", "People should not judge others before understanding them", "Art class is the most important subject", "Being new at school is always fun"], correct: 1, hint: "Think about how the other kids misunderstood Sofia and what Ethan discovered.", explanation: "The story teaches that we shouldn't judge others without understanding their situation first!" },
            { id: 2844, storyId: 148, category: "inference", type: "multiple", question: "Why did Sofia always sit in the front row of class?", options: ["She wanted to impress the teacher", "She couldn't see the board from far away", "She needed to read the teacher's lips since she is deaf", "She always arrived early to class"], correct: 2, hint: "Think about what Ethan learned about Sofia and how she communicates.", explanation: "Since Sofia is deaf and reads lips, sitting in the front row helped her understand what the teacher was saying!" },
            { id: 2845, storyId: 148, category: "vocabulary", type: "multiple", question: "What does 'hyperrealistic' mean when describing Sofia's drawing?", options: ["Extremely lifelike and detailed", "Brightly colored and abstract", "Quickly sketched and rough", "Copied from a photograph"], correct: 0, hint: "The passage says the drawing captured 'every detail' of their teacher.", explanation: "'Hyperrealistic' means extremely realistic--the drawing looked almost like a photograph!" },
            { id: 2846, storyId: 148, category: "sequence", type: "multiple", question: "What did Ethan do BEFORE he brought his lunch to the art room?", options: ["He learned sign language", "He noticed Sofia sitting alone drawing in the art room", "He talked to Sofia about her deafness", "He introduced Sofia to his friends"], correct: 1, hint: "What first caught Ethan's attention about Sofia?", explanation: "Ethan first noticed Sofia sitting alone in the art room with her sketchpad, then decided to bring his lunch there the next day!" },
            { id: 2847, storyId: 148, category: "character", type: "multiple", question: "What character trait does Ethan show throughout this story?", options: ["He is nosy and gossipy", "He is kind and willing to make an effort to connect", "He is shy and avoids new people", "He is competitive and wants to be the best artist"], correct: 1, hint: "Think about how Ethan approaches Sofia compared to the other kids.", explanation: "Ethan shows kindness by sitting with Sofia, appreciating her art, and learning sign language to communicate with her!" },
            { id: 2848, storyId: 148, category: "main_idea", type: "multiple", question: "What is the main idea of 'The New Kid's Secret'?", options: ["Ethan befriends Sofia by taking time to understand her instead of believing rumors", "Sofia is the best artist in the school", "New students should always eat lunch alone", "Ethan wants to learn how to draw"], correct: 0, hint: "What is the most important thing that happens between Ethan and Sofia?", explanation: "The story is about Ethan making the effort to understand Sofia rather than believing the rumors about her!" },
            { id: 2849, storyId: 148, category: "cause_effect", type: "multiple", question: "What caused the other kids to think Sofia was arrogant?", options: ["She bragged about her artistic talent", "She never spoke in class and they didn't understand why", "She refused to share her drawings", "She told them she didn't want to be friends"], correct: 1, hint: "What did the other kids not know about Sofia?", explanation: "Because the kids didn't know Sofia was deaf, they misinterpreted her silence as arrogance!" },
            { id: 2850, storyId: 148, category: "compare_contrast", type: "multiple", question: "How does Ethan's approach to Sofia differ from the other students' approach?", options: ["Ethan spreads rumors while others are kind to her", "Ethan ignores her while others try to talk to her", "Ethan makes the effort to sit with her while others gossip and avoid her", "Ethan tells the teacher while others keep quiet"], correct: 2, hint: "Compare what the other kids do (spread rumors) with what Ethan does.", explanation: "While other students whispered rumors and avoided Sofia, Ethan sat with her and took the time to understand her!" },
            { id: 2851, storyId: 148, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Sofia was the most talented artist in the school", "Ethan was the nicest kid in class", "Sofia had transferred from a school three states away", "The art room was the best place to eat lunch"], correct: 2, hint: "Which statement can be verified directly from the text?", explanation: "The passage directly states that Sofia 'had transferred from a school three states away'!" },
            { id: 2852, storyId: 148, category: "author_purpose", type: "multiple", question: "Why did the author include the detail about rumors swirling around Sofia?", options: ["To show how people make wrong assumptions when they don't understand someone", "To make Sofia seem like a mysterious villain", "To explain why the school has a gossip problem", "To show that rumors are always true"], correct: 0, hint: "What do the rumors reveal about how people treat what they don't understand?", explanation: "The author uses the rumors to show how quickly people misjudge others when they don't take time to understand!" },
            { id: 2853, storyId: 148, category: "text_structure", type: "multiple", question: "How is 'The New Kid's Secret' organized?", options: ["As a problem-solution story where curiosity leads to understanding", "As a debate about whether deaf students should attend regular schools", "As a list of tips for making new friends", "As a comparison between art and language"], correct: 0, hint: "Think about the problem (misunderstanding) and how it gets resolved.", explanation: "The story follows a problem-solution structure: the problem of misunderstanding Sofia is solved when Ethan takes the time to connect!" },
            { id: 2854, storyId: 148, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Sofia smiled shyly and wrote on paper.", answers: {"0": "noun", "1": "verb", "2": "adverb", "5": "noun"}, hint: "Look for who does the action, what the actions are, how an action is done, and the thing.", explanation: "Sofia is a noun (name), smiled is a verb (action), shyly is an adverb (how she smiled), and paper is a noun (thing)!" },

// Story 149: The Whispering Woods (O) - Fiction
// IDs 2855-2866
            { id: 2855, storyId: 149, category: "theme", type: "multiple", question: "What is the main theme of 'The Science Fair Surprise'?", options: ["Science is too difficult for students", "Curiosity and careful observation can lead to unexpected discoveries", "Winning prizes is the most important part of science", "Students should always follow instructions exactly"], correct: 1, hint: "Think about how the student's experiment led to a surprising result.", explanation: "The story shows that being curious and paying close attention during experiments can lead to surprising and exciting discoveries!" },
            { id: 2856, storyId: 149, category: "inference", type: "multiple", question: "Why was the student's discovery so surprising to the judges?", options: ["The student was too young to do real science", "The project looked messy and unprofessional", "The student found unexpected results that challenged what people assumed", "The judges did not understand the experiment"], correct: 2, hint: "Think about why the results were considered remarkable.", explanation: "The judges were impressed because the student's careful work revealed something no one expected, showing real scientific thinking!" },
            { id: 2857, storyId: 149, category: "vocabulary", type: "multiple", question: "What does 'hypothesis' mean in a science fair project?", options: ["The final results of an experiment", "An educated guess or prediction that can be tested", "The materials needed for an experiment", "A type of award given at science fairs"], correct: 1, hint: "This is something you create before you start experimenting.", explanation: "A hypothesis is an educated guess or prediction about what will happen, which the experiment then tests!" },
            { id: 2858, storyId: 149, category: "sequence", type: "multiple", question: "What happened AFTER the student noticed the unexpected results?", options: ["The student gave up on the project", "The student repeated the experiment to make sure the results were accurate", "The student changed the hypothesis to match what they wanted", "The student asked a friend to finish the project"], correct: 1, hint: "What does a good scientist do when they get surprising results?", explanation: "A good scientist repeats the experiment to verify the results, which is exactly what the student did before presenting the findings!" },
            { id: 2859, storyId: 149, category: "character", type: "multiple", question: "What character traits does the student display in this story?", options: ["Laziness and impatience with details", "Curiosity, persistence, and honesty about results", "Competitiveness and a desire to beat other students", "Nervousness and a lack of confidence"], correct: 1, hint: "Think about how the student handled the unexpected discovery.", explanation: "The student showed curiosity by investigating further, persistence by repeating experiments, and honesty by reporting true results!" },
            { id: 2860, storyId: 149, category: "main_idea", type: "multiple", question: "What is the main idea of 'The Science Fair Surprise'?", options: ["A student's careful experiment at a science fair leads to an unexpected and exciting discovery", "Science fairs are stressful competitions that students dislike", "Only professional scientists can make real discoveries", "The student won first place easily without much effort"], correct: 0, hint: "What is the most important thing that happens in the story?", explanation: "The story is about a student whose careful scientific work during a science fair leads to a surprising discovery that impresses everyone!" },
            { id: 2861, storyId: 149, category: "cause_effect", type: "multiple", question: "What caused the student to realize the experiment had produced unusual results?", options: ["A teacher pointed out the error", "The student carefully recorded observations and noticed the data did not match expectations", "Another student copied the same experiment", "The results matched the hypothesis perfectly"], correct: 1, hint: "How did the student figure out something unexpected had happened?", explanation: "By carefully recording all observations, the student noticed that the actual data was different from what was predicted!" },
            { id: 2862, storyId: 149, category: "compare_contrast", type: "multiple", question: "How did the student's expectations BEFORE the experiment compare to the actual results?", options: ["The student expected one outcome but discovered something completely different", "The results were exactly as predicted from the beginning", "The student had no expectations at all before starting", "The experiment failed and produced no results"], correct: 0, hint: "Think about what the student predicted versus what actually happened.", explanation: "The student had a hypothesis about what would happen, but the actual results were surprisingly different, which made the discovery exciting!" },
            { id: 2863, storyId: 149, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the story?", options: ["The science fair was the most exciting event of the year", "The student's project was the best one at the fair", "The student repeated the experiment to verify the results", "Science fairs should be required at every school"], correct: 2, hint: "Which statement describes something that actually happened rather than a personal judgment?", explanation: "The story states that the student repeated the experiment to check the results -- this is a verifiable fact from the story!" },
            { id: 2864, storyId: 149, category: "author_purpose", type: "multiple", question: "Why did the author write this story about a science fair discovery?", options: ["To teach readers how to win science fair prizes", "To show that real science involves curiosity, careful work, and being open to surprises", "To argue that science fairs are better than other school events", "To explain complicated chemistry formulas"], correct: 1, hint: "What lesson does the reader take away from the story?", explanation: "The author wants to show that good science comes from curiosity, careful observation, and being willing to follow the evidence even when it surprises you!" },
            { id: 2865, storyId: 149, category: "text_structure", type: "multiple", question: "How is 'The Science Fair Surprise' organized?", options: ["As a list of science fair rules and guidelines", "As a chronological narrative following the student from preparation through discovery", "As a comparison between different science fair projects", "As a persuasive essay about why science matters"], correct: 1, hint: "Think about how the story moves from beginning to end.", explanation: "The story follows a chronological structure, taking the reader through the student's preparation, experimentation, surprising discovery, and presentation!" },
            { id: 2866, storyId: 149, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "The student carefully recorded each observation in a notebook.", answers: {"1": "noun", "2": "adverb", "3": "verb", "5": "noun", "8": "noun"}, hint: "Look for the person, how they did the action, the action itself, and the things mentioned.", explanation: "Student is a noun (person), carefully is an adverb (how they recorded), recorded is a verb (action), observation is a noun (thing), and notebook is a noun (thing)!" },

// Story 150: Championship Decision (O) - Fiction
// IDs 2867-2878
            { id: 2867, storyId: 150, category: "theme", type: "multiple", question: "What is the main theme of 'Championship Decision'?", options: ["Winning championships is the most important thing in life", "True friendship and loyalty matter more than personal achievements", "Swimming is a difficult and demanding sport", "Parents should make decisions for their children"], correct: 1, hint: "Think about what Jordan chose to do and why.", explanation: "The story teaches that being there for someone you love is more important than winning a championship!" },
            { id: 2868, storyId: 150, category: "inference", type: "multiple", question: "What can you infer about why Jordan's mother said 'I can't decide for you'?", options: ["She didn't care about Jordan's swimming career", "She wanted Jordan to learn to make important moral decisions on her own", "She was too busy to help Jordan decide", "She thought Jordan should definitely go to the race"], correct: 1, hint: "Think about why a parent might not give their child the answer directly.", explanation: "Jordan's mother wanted her to develop her own values by making this difficult choice herself!" },
            { id: 2869, storyId: 150, category: "vocabulary", type: "multiple", question: "What does 'stable' mean when the passage says 'Aaliyah's mother was stable'?", options: ["She was standing up and walking around", "Her medical condition was no longer getting worse", "She was completely healed and ready to leave", "She was sitting in a stable with horses"], correct: 1, hint: "This word is used in a medical context about someone who had a heart attack.", explanation: "In a medical setting, 'stable' means a patient's condition has stopped getting worse and is now steady!" },
            { id: 2870, storyId: 150, category: "sequence", type: "multiple", question: "What is the correct order of events in this story?", options: ["Jordan gets a text, talks to her mom, drives to the hospital, stays all night", "Jordan drives to the hospital, gets a text, talks to her mom, swims the race", "Jordan swims the race, then visits Aaliyah at the hospital", "Jordan talks to the scouts, then drives to the hospital"], correct: 0, hint: "Follow the timeline from when Jordan gets the text message.", explanation: "Jordan first gets Aaliyah's text, then her mom helps her think, then she drives to the hospital and stays all night!" },
            { id: 2871, storyId: 150, category: "character", type: "multiple", question: "What does Jordan's decision reveal about her character?", options: ["She is selfish and only cares about herself", "She is compassionate and values people over personal success", "She is indecisive and can't make up her mind", "She doesn't really care about swimming"], correct: 1, hint: "Think about what Jordan gave up and why she did it.", explanation: "Jordan gave up a championship with university scouts watching because she valued her friendship with Aaliyah more!" },
            { id: 2872, storyId: 150, category: "main_idea", type: "multiple", question: "What is the main idea of 'Championship Decision'?", options: ["Jordan chooses to support her best friend over competing in a championship", "Jordan wins the state swimming championship", "Aaliyah's mother recovers from a heart attack", "Jordan gets a scholarship from university scouts"], correct: 0, hint: "What is the most important decision in the story?", explanation: "The story centers on Jordan's choice to be with Aaliyah at the hospital instead of swimming in the championship!" },
            { id: 2873, storyId: 150, category: "cause_effect", type: "multiple", question: "What caused Jordan to miss the state swimming championship?", options: ["She was injured during practice", "She was sick and couldn't swim", "She chose to go to the hospital to be with Aaliyah after her mom's heart attack", "The championship was cancelled due to weather"], correct: 2, hint: "Why did Jordan decide not to swim?", explanation: "Jordan chose to go to the hospital because her best friend Aaliyah needed her after Aaliyah's mother had a heart attack!" },
            { id: 2874, storyId: 150, category: "compare_contrast", type: "multiple", question: "What two things is Jordan weighing when she makes her decision?", options: ["Swimming practice vs. homework", "The championship and scholarship opportunities vs. being there for her friend", "Moving to a new city vs. staying at her current school", "Joining the swim team vs. joining the art club"], correct: 1, hint: "What could Jordan gain by racing, and what would she lose by not going to Aaliyah?", explanation: "Jordan weighs the championship, scouts, and scholarship against being there for Aaliyah when she needs her most!" },
            { id: 2875, storyId: 150, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Jordan was the best swimmer in the entire state", "Aaliyah's mother was the kindest person Jordan knew", "Jordan was ranked first in the 100-meter butterfly", "Going to the hospital was definitely the right decision"], correct: 2, hint: "Which statement can be verified from the text without personal judgment?", explanation: "The passage directly states Jordan 'was ranked first in the 100-meter butterfly'--this is a factual ranking!" },
            { id: 2876, storyId: 150, category: "author_purpose", type: "multiple", question: "Why did the author mention that Jordan had trained for three years and scouts were watching?", options: ["To show how much Jordan was sacrificing by choosing her friend", "To explain the rules of competitive swimming", "To make Jordan seem like a bad friend", "To promote university swimming programs"], correct: 0, hint: "How does knowing about the years of training affect how you view Jordan's choice?", explanation: "By emphasizing the stakes--three years of training and scouts watching--the author shows the enormous sacrifice Jordan made!" },
            { id: 2877, storyId: 150, category: "text_structure", type: "multiple", question: "How is 'Championship Decision' organized?", options: ["As a story building to a moral dilemma and its resolution", "As a step-by-step guide to competitive swimming", "As a comparison between two different swimmers", "As a flashback to Jordan's early swimming days"], correct: 0, hint: "Think about how the story sets up the conflict and shows Jordan making her choice.", explanation: "The story builds up the stakes (championship, scouts) then presents a moral dilemma that Jordan resolves by choosing friendship!" },
            { id: 2878, storyId: 150, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Jordan thought about the scouts, the scholarship opportunities, years of early morning practices.", answers: {"0": "noun", "1": "verb", "4": "noun", "7": "noun"}, hint: "Look for who does the action, what the action is, and the things being thought about.", explanation: "Jordan is a noun (name), thought is a verb (action), scouts is a noun (people), and scholarship is a noun (thing)!" },

// Story 151: Letters from 1957 (O) - Fiction
// IDs 2879-2890
            { id: 2879, storyId: 151, category: "theme", type: "multiple", question: "What is the main theme of 'The Time Capsule in Grandpa's Workshop'?", options: ["Old things should be thrown away", "Connecting with family history and sharing skills across generations creates meaningful bonds", "Workshops are dangerous places for children", "Grandparents forget important things"], correct: 1, hint: "Think about what happens when Harper and Grandpa Walt open the time capsule together.", explanation: "The story shows how discovering Grandpa Walt's childhood treasures leads to a new connection when Harper asks him to teach her woodcarving!" },
            { id: 2880, storyId: 151, category: "inference", type: "multiple", question: "Why did Grandpa Walt's face light up when Harper asked him to teach her to carve?", options: ["He wanted to sell carved items at a market", "He was excited to share a skill passed down from his own grandfather", "He needed help finishing a project", "He was surprised Harper could talk"], correct: 1, hint: "Think about who taught Grandpa Walt to carve and what it would mean to pass that skill along.", explanation: "Grandpa Walt learned carving from his grandfather, so Harper's request meant he could continue a family tradition across another generation!" },
            { id: 2881, storyId: 151, category: "vocabulary", type: "multiple", question: "What does 'remarkably' mean when Harper noticed the airplane was 'remarkably detailed'?", options: ["Slightly and barely", "In a way that is surprising and impressive", "Poorly and roughly", "Quickly and carelessly"], correct: 1, hint: "Harper was impressed enough to ask if Grandpa Walt really carved it himself.", explanation: "'Remarkably' means in a way that is worthy of attention or surprisingly impressive--the carving was so detailed it amazed Harper!" },
            { id: 2882, storyId: 151, category: "sequence", type: "multiple", question: "What happened AFTER Harper and Grandpa Walt opened the time capsule?", options: ["They buried it again immediately", "They read the letter with predictions, laughed, then Harper asked to learn carving", "They called the newspaper to report the discovery", "They threw everything away"], correct: 1, hint: "What did they find inside, and what did Harper notice about the wooden airplane?", explanation: "After opening the capsule, they laughed at young Walt's predictions, Harper admired the carved airplane, and she asked Grandpa to teach her!" },
            { id: 2883, storyId: 151, category: "character", type: "multiple", question: "What does Harper's request to learn carving show about her character?", options: ["She is bored and has nothing else to do", "She is curious and values family connections and learning new skills", "She wants to make money selling carvings", "She feels sorry for her grandfather"], correct: 1, hint: "Why would seeing the carved airplane inspire Harper to want to learn?", explanation: "Harper's request shows curiosity and a desire to connect with her grandfather by learning the same skill his grandfather taught him!" },
            { id: 2884, storyId: 151, category: "main_idea", type: "multiple", question: "What is the main idea of this story?", options: ["Harper and her grandfather discover a forgotten time capsule that reconnects them to family history and inspires a new shared hobby", "Harper finds buried treasure worth a lot of money", "Grandpa Walt is too old to remember anything", "Time capsules are boring"], correct: 0, hint: "What is the most important thing that happens because of the time capsule discovery?", explanation: "The story is about how finding the time capsule connects Harper to her grandfather's past and inspires her to learn woodcarving from him!" },
            { id: 2885, storyId: 151, category: "cause_effect", type: "multiple", question: "What caused Harper to ask Grandpa Walt to teach her carving?", options: ["Her teacher assigned it as homework", "She saw the remarkably detailed wooden airplane he had carved as a child", "Her mother told her to learn a new hobby", "She wanted to win a carving contest"], correct: 1, hint: "What specific item in the time capsule inspired Harper?", explanation: "Seeing the beautifully detailed wooden airplane that young Walt had carved inspired Harper to want to learn the same skill!" },
            { id: 2886, storyId: 151, category: "compare_contrast", type: "multiple", question: "How do young Walt's predictions about the future compare with what actually happened?", options: ["All of his predictions came true perfectly", "Most predictions like robot butlers and moon cities did not come true, but self-tying shoes did", "None of his predictions were even close", "He predicted the internet and smartphones"], correct: 1, hint: "Grandpa Walt said 'I got one right' about which prediction?", explanation: "Young Walt predicted robot butlers, moon cities, and self-tying shoes, but only the shoes prediction came true!" },
            { id: 2887, storyId: 151, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["The wooden airplane was the best carving ever made", "Grandpa Walt was the funniest grandfather in town", "The time capsule lid was scratched with 'DO NOT OPEN UNTIL 2025'", "Everyone should make a time capsule"], correct: 2, hint: "Which statement can be verified directly from the text?", explanation: "The passage states that scratched into the lid were the words 'DO NOT OPEN UNTIL 2025'--this is a verifiable detail from the story!" },
            { id: 2888, storyId: 151, category: "author_purpose", type: "multiple", question: "Why did the author include the detail that Grandpa Walt's grandfather taught him to carve?", options: ["To show that skills and traditions are passed down through generations in families", "To explain why workshops are messy", "To prove that carving is easy to learn", "To describe what life was like in 1975"], correct: 0, hint: "Think about the chain: great-grandfather taught Grandpa Walt, and now Harper wants to learn.", explanation: "This detail shows how family traditions pass from generation to generation, and Harper continuing the tradition gives the story its heartwarming ending!" },
            { id: 2889, storyId: 151, category: "text_structure", type: "multiple", question: "How is this story organized?", options: ["As a discovery narrative: finding the capsule, exploring its contents, and being inspired to create something new", "As a list of items found in the workshop", "As a comparison between 1975 and today", "As a set of instructions for making a time capsule"], correct: 0, hint: "Think about the sequence: discovery, exploration, and inspiration.", explanation: "The story follows a discovery structure: Harper finds the capsule, they explore its contents together, and the discovery inspires her to learn carving!" },
            { id: 2890, storyId: 151, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Harper discovered a metal box buried beneath old newspapers.", answers: {"0": "noun", "1": "verb", "3": "adjective", "4": "noun", "6": "adjective", "7": "noun"}, hint: "Look for who does the action, what the action is, the things, and what describes a thing.", explanation: "Harper is a noun (name), discovered is a verb (action), metal is an adjective (describes box), box is a noun (thing), old is an adjective (describes newspapers), and newspapers is a noun (thing)!" },

// Story 152: Nature's Living Lights (O) - Nonfiction
// IDs 2891-2902
            { id: 2891, storyId: 152, category: "theme", type: "multiple", question: "What is the main theme of 'Nature's Living Lights'?", options: ["Bioluminescence is a remarkable natural ability with important scientific applications", "The ocean is too dark for any life to survive", "Light bulbs are better than natural light", "Scientists should stop studying the ocean"], correct: 0, hint: "Think about what the passage explains about bioluminescence and why it matters.", explanation: "The passage highlights how bioluminescence is an amazing natural ability that scientists are studying for human benefits!" },
            { id: 2892, storyId: 152, category: "inference", type: "multiple", question: "Why is the deep-sea dragonfish's red light described as 'invisible night vision'?", options: ["The dragonfish can't actually see its own light", "Most deep-sea animals cannot see red light, so the dragonfish can see them without being detected", "Red light doesn't work underwater", "The dragonfish is actually blind"], correct: 1, hint: "Think about what advantage the dragonfish has if other animals can't see red light.", explanation: "Since most deep-sea animals cannot see red light, the dragonfish can illuminate and see prey without being noticed!" },
            { id: 2893, storyId: 152, category: "vocabulary", type: "multiple", question: "What does 'efficient' mean when the passage says bioluminescent light is 'incredibly efficient'?", options: ["Very bright and blinding", "Producing light with very little wasted energy", "Extremely expensive to produce", "Only lasting for a short time"], correct: 1, hint: "The passage compares bioluminescent light to light bulbs that waste energy as heat.", explanation: "'Efficient' means producing results with little waste--bioluminescent light creates light without wasting energy as heat!" },
            { id: 2894, storyId: 152, category: "sequence", type: "multiple", question: "According to the passage, what is the correct order of the bioluminescence chemical process?", options: ["Luciferin and luciferase combine with oxygen to create light", "Light creates oxygen that produces luciferin", "Oxygen breaks down luciferin to create heat", "Luciferase absorbs sunlight and stores it"], correct: 0, hint: "Look for the two substances and what they combine with.", explanation: "The passage states that luciferin and luciferase combine with oxygen to create light without heat!" },
            { id: 2895, storyId: 152, category: "character", type: "multiple", question: "What perspective do the scientists in this passage represent?", options: ["They are fearful of deep-sea creatures", "They are curious researchers finding practical uses for bioluminescence", "They believe bioluminescence is unimportant", "They only study bioluminescence for entertainment"], correct: 1, hint: "Think about what scientists are doing with their knowledge of bioluminescence.", explanation: "Scientists are shown as curious researchers applying bioluminescence to medicine, lighting, and ecosystem exploration!" },
            { id: 2896, storyId: 152, category: "main_idea", type: "multiple", question: "What is the main idea of 'Nature's Living Lights'?", options: ["Light bulbs waste too much energy", "Deep-sea creatures use bioluminescence for survival, and scientists are finding human applications for it", "The ocean is completely dark below the surface", "Jellyfish are the only animals that glow"], correct: 1, hint: "What are the two big points the passage makes about bioluminescence?", explanation: "The passage explains how animals use bioluminescence to survive AND how scientists are applying it for human benefit!" },
            { id: 2897, storyId: 152, category: "cause_effect", type: "multiple", question: "Why do some jellyfish release glowing clouds?", options: ["To attract mates", "To confuse predators while escaping", "To light their way in the dark ocean", "To communicate with other jellyfish"], correct: 1, hint: "Think about what problem the jellyfish is trying to solve.", explanation: "Jellyfish release glowing clouds to confuse predators, giving themselves time to escape!" },
            { id: 2898, storyId: 152, category: "compare_contrast", type: "multiple", question: "How does bioluminescent light compare to light from light bulbs?", options: ["Both waste the same amount of energy", "Bioluminescent light creates light without heat, while light bulbs waste energy as heat", "Light bulbs are more efficient than bioluminescence", "Bioluminescence produces more heat than light bulbs"], correct: 1, hint: "The passage directly compares these two types of light.", explanation: "The passage states that bioluminescent light is efficient because it creates light without heat, unlike wasteful light bulbs!" },
            { id: 2899, storyId: 152, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Bioluminescence is the most beautiful phenomenon in nature", "Deep-sea creatures are the most interesting animals on Earth", "Scientists estimate that ninety percent of deep-sea animals can produce light", "The dragonfish is the coolest animal in the ocean"], correct: 2, hint: "Which statement uses specific data from the passage?", explanation: "The passage states that 'scientists estimate that ninety percent of deep-sea animals can produce light'--a verifiable fact!" },
            { id: 2900, storyId: 152, category: "author_purpose", type: "multiple", question: "Why did the author describe specific animals like anglerfish, firefly squid, and dragonfish?", options: ["To give concrete examples of how different animals use bioluminescence", "To argue that these are the only animals with bioluminescence", "To scare readers about dangerous ocean creatures", "To explain why people should not go deep-sea diving"], correct: 0, hint: "How do these examples help the reader understand bioluminescence?", explanation: "The author uses specific animal examples to show the variety of ways creatures use bioluminescence for different purposes!" },
            { id: 2901, storyId: 152, category: "text_structure", type: "multiple", question: "How is 'Nature's Living Lights' organized?", options: ["As a chronological history of bioluminescence discoveries", "By explaining what bioluminescence is, how animals use it, and how humans apply it", "As a comparison between land and sea animals", "As a persuasive argument to protect the ocean"], correct: 1, hint: "Think about the three main sections of the passage.", explanation: "The passage moves from explaining what bioluminescence is, to animal uses, to human scientific applications!" },
            { id: 2902, storyId: 152, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Anglerfish dangle glowing lures to attract prey.", answers: {"0": "noun", "1": "verb", "2": "adjective", "3": "noun"}, hint: "Look for the animal, what it does, what describes the lures, and the things mentioned.", explanation: "Anglerfish is a noun (animal), dangle is a verb (action), glowing is an adjective (describes lures), and lures is a noun (things)!" },

// Story 153: How Video Games Are Made (O) - Nonfiction
// IDs 2903-2914
            { id: 2903, storyId: 153, category: "theme", type: "multiple", question: "What is the main theme of 'How Video Games Are Made'?", options: ["Playing video games is easy and fun", "Creating video games is a complex, collaborative process involving many professionals over years", "Programming is the only important part of game development", "Video games are a waste of time"], correct: 1, hint: "Think about how many people and steps are involved in making a game.", explanation: "The passage emphasizes that game development requires hundreds of creative professionals working together for years!" },
            { id: 2904, storyId: 153, category: "inference", type: "multiple", question: "Why are many games abandoned during the prototyping stage?", options: ["The programmers get bored with the project", "Testing reveals that the game mechanics don't work well or aren't fun", "The company runs out of paper for design documents", "Players don't buy the prototypes"], correct: 1, hint: "The passage says games are abandoned when 'testing reveals problems.'", explanation: "Prototyping tests core mechanics like jumping and difficulty balance--if these don't work, the game isn't worth continuing!" },
            { id: 2905, storyId: 153, category: "vocabulary", type: "multiple", question: "What does 'fundamental' mean when the passage says designers ask 'fundamental questions'?", options: ["Unimportant and minor", "Basic and essential", "Confusing and complicated", "Funny and entertaining"], correct: 1, hint: "These are the first and most important questions designers ask.", explanation: "'Fundamental' means basic and essential--these are the core questions that everything else builds upon!" },
            { id: 2906, storyId: 153, category: "sequence", type: "multiple", question: "What is the correct order of game development phases described in the passage?", options: ["Concept phase, prototyping, full production, quality assurance, marketing and launch", "Marketing, prototyping, concept phase, launch", "Full production, concept phase, quality assurance, prototyping", "Quality assurance, marketing, full production, concept phase"], correct: 0, hint: "Follow the order the passage describes each phase.", explanation: "The passage describes: concept phase first, then prototyping, full production, quality assurance, and finally marketing and launch!" },
            { id: 2907, storyId: 153, category: "character", type: "multiple", question: "What role do quality assurance testers play in game development?", options: ["They design the characters and environments", "They write the game's story and dialogue", "They play the game repeatedly to find bugs that need fixing", "They create the marketing trailers"], correct: 2, hint: "The passage mentions testers searching for something specific.", explanation: "Quality assurance testers play the game repeatedly to find bugs--a typical major game might have over 10,000 bugs to fix!" },
            { id: 2908, storyId: 153, category: "main_idea", type: "multiple", question: "What is the main idea of 'How Video Games Are Made'?", options: ["Video games take years and hundreds of professionals across many disciplines to create", "Programming is the only step in making video games", "Video games are made by a single person in a few weeks", "Marketing is the most important part of game development"], correct: 0, hint: "What does the passage emphasize about the game development process?", explanation: "The passage shows that games require years of work by hundreds of professionals including artists, writers, programmers, and testers!" },
            { id: 2909, storyId: 153, category: "cause_effect", type: "multiple", question: "What is the effect of sound designers crafting music for a game?", options: ["It makes the game file larger", "It enhances the emotional impact of the game experience", "It slows down the development process", "It replaces the need for visual effects"], correct: 1, hint: "The passage explains what good music does for a game.", explanation: "Sound designers craft music that 'enhances emotional impact,' making players feel more connected to the game experience!" },
            { id: 2910, storyId: 153, category: "compare_contrast", type: "multiple", question: "How does the time it takes to CREATE a game compare to the time players spend EXPERIENCING it?", options: ["Both take about the same amount of time", "Players experience in hours what took thousands of people years to create", "Creating a game takes less time than playing it", "Players spend years playing while developers spend hours making games"], correct: 1, hint: "Look at the last sentence of the passage.", explanation: "The passage states that 'players experience in hours what took thousands of people years to create'!" },
            { id: 2911, storyId: 153, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Video games are the best form of entertainment", "All video games should take at least five years to develop", "A typical major game might have over 10,000 bugs requiring fixes before release", "Programming is the most difficult part of game development"], correct: 2, hint: "Which statement uses a specific number from the passage?", explanation: "The passage states that 'a typical major game might have over 10,000 bugs requiring fixes'--a specific, verifiable claim!" },
            { id: 2912, storyId: 153, category: "author_purpose", type: "multiple", question: "Why did the author write 'How Video Games Are Made'?", options: ["To convince readers to stop playing video games", "To inform readers about the detailed process behind video game creation", "To argue that one game company is better than another", "To teach readers how to become programmers"], correct: 1, hint: "What does the reader learn by the end of the passage?", explanation: "The author's purpose is to inform readers about all the steps, people, and effort involved in creating video games!" },
            { id: 2913, storyId: 153, category: "text_structure", type: "multiple", question: "How is 'How Video Games Are Made' organized?", options: ["As a sequential process describing each phase of game development in order", "As a comparison between good and bad video games", "As a persuasive argument for more video game funding", "As a collection of random facts about gaming"], correct: 0, hint: "Notice how the passage moves through each development phase.", explanation: "The passage is organized sequentially, walking through each phase from concept to launch in order!" },
            { id: 2914, storyId: 153, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Programmers build simple versions to test core mechanics.", answers: {"0": "noun", "1": "verb", "2": "adjective", "3": "noun"}, hint: "Look for who does the action, what the action is, what describes the thing, and the things.", explanation: "Programmers is a noun (people), build is a verb (action), simple is an adjective (describes versions), and versions is a noun (things)!" },

// Story 154: When Weather Turns Deadly (O) - Nonfiction
// IDs 2915-2926
            { id: 2915, storyId: 154, category: "theme", type: "multiple", question: "What is the main theme of 'How Weather Satellites Track Storms'?", options: ["Weather satellites are too expensive to be useful", "Technology in space helps scientists monitor and predict storms to keep people safe", "Storms are impossible to predict accurately", "Satellites are only useful for taking photographs"], correct: 1, hint: "Think about why weather satellites matter for communities.", explanation: "The passage shows that satellite technology orbiting Earth helps scientists track storms and warn people, saving lives!" },
            { id: 2916, storyId: 154, category: "inference", type: "multiple", question: "Why do weather satellites orbit at different altitudes?", options: ["Higher satellites are cheaper to launch", "Different altitudes provide different types of useful weather information", "Lower satellites take better photographs of the ground", "Scientists cannot control where satellites end up"], correct: 1, hint: "Think about what each type of orbit allows scientists to observe.", explanation: "Some satellites orbit high to see large weather patterns across continents, while others orbit lower to get detailed close-up data about specific storms!" },
            { id: 2917, storyId: 154, category: "vocabulary", type: "multiple", question: "What does 'geostationary' mean when describing a weather satellite's orbit?", options: ["Moving rapidly around the Earth", "Staying above the same spot on Earth by matching Earth's rotation", "Orbiting close to the ground", "Traveling in a zigzag pattern"], correct: 1, hint: "The prefix 'geo' relates to Earth, and 'stationary' means staying still.", explanation: "'Geostationary' means the satellite orbits at the same speed as Earth's rotation, so it stays above the same location continuously!" },
            { id: 2918, storyId: 154, category: "sequence", type: "multiple", question: "What is the correct sequence for how satellite data helps predict storms?", options: ["Warning is issued, then data is collected, then computers analyze it", "Satellites collect data, computers process it into models, and meteorologists issue forecasts", "Meteorologists guess, then satellites confirm, then computers check", "Computers generate storms, satellites photograph them, then warnings go out"], correct: 1, hint: "Think about the order: gathering information, processing it, and sharing predictions.", explanation: "First satellites gather data, then powerful computers analyze it using weather models, and finally meteorologists use the results to create forecasts and warnings!" },
            { id: 2919, storyId: 154, category: "character", type: "multiple", question: "What perspective does the author present about weather satellite technology?", options: ["Satellites are unreliable and often give wrong information", "Weather satellites are a valuable tool that has greatly improved storm tracking and safety", "Only wealthy countries benefit from satellite technology", "Satellites will eventually replace all other weather tools"], correct: 1, hint: "How does the author describe the impact of weather satellites?", explanation: "The author presents weather satellites as important tools that have dramatically improved our ability to track storms and protect communities!" },
            { id: 2920, storyId: 154, category: "main_idea", type: "multiple", question: "What is the main idea of 'How Weather Satellites Track Storms'?", options: ["Weather satellites use advanced technology to monitor storms from space, helping scientists predict dangerous weather and save lives", "Satellites are the only tool meteorologists use", "Weather prediction is still mostly guesswork", "Building satellites is the most difficult engineering challenge"], correct: 0, hint: "What is the passage mainly about?", explanation: "The passage explains how weather satellites use sensors and cameras from space to track storms, feed data to computers, and help forecasters warn people!" },
            { id: 2921, storyId: 154, category: "cause_effect", type: "multiple", question: "What causes weather satellites to be able to track a storm's movement over time?", options: ["Satellites can hear thunder from space", "Satellites continuously capture images that show how clouds and storms change position", "Ground stations push storms toward the satellites", "Storms always follow the same path"], correct: 1, hint: "Think about how taking pictures over time shows movement.", explanation: "By taking continuous images from space, satellites create a time sequence that shows exactly where a storm is moving and how it is changing!" },
            { id: 2922, storyId: 154, category: "compare_contrast", type: "multiple", question: "How do geostationary satellites differ from polar-orbiting satellites?", options: ["Geostationary satellites are smaller and less expensive", "Geostationary satellites stay over one area continuously, while polar-orbiting satellites circle the entire Earth", "Polar-orbiting satellites are older technology", "There is no difference between the two types"], correct: 1, hint: "Compare where each type of satellite travels and what it can observe.", explanation: "Geostationary satellites hover over one spot for continuous monitoring, while polar-orbiting satellites circle the globe to scan the entire planet!" },
            { id: 2923, storyId: 154, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Weather satellites are the most amazing invention ever created", "Satellite images are prettier than radar images", "Weather satellites orbit Earth and collect data about atmospheric conditions", "Everyone should become a meteorologist"], correct: 2, hint: "Which statement describes something verifiable rather than a personal opinion?", explanation: "The passage states that weather satellites orbit Earth and collect atmospheric data -- this is a verifiable fact!" },
            { id: 2924, storyId: 154, category: "author_purpose", type: "multiple", question: "Why did the author write about how weather satellites track storms?", options: ["To convince readers to become astronauts", "To help readers understand the technology that makes weather forecasting possible", "To argue that satellites are better than ground stations", "To entertain readers with stories about space"], correct: 1, hint: "What does the reader learn from this passage?", explanation: "The author explains how satellite technology works so readers can appreciate the science behind the weather forecasts they rely on every day!" },
            { id: 2925, storyId: 154, category: "text_structure", type: "multiple", question: "How is 'How Weather Satellites Track Storms' organized?", options: ["As a personal narrative about a meteorologist's career", "By explaining different types of satellites, the data they collect, and how that data is used for forecasting", "As a debate about whether satellites are worth the cost", "In chronological order of every satellite launch"], correct: 1, hint: "Notice how the passage moves from describing satellites to explaining their data and its uses.", explanation: "The passage is organized by topic -- it describes satellite types, the data they collect, and how scientists use that data to track and predict storms!" },
            { id: 2926, storyId: 154, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Satellites continuously capture detailed images of swirling storms.", answers: {"0": "noun", "1": "adverb", "2": "verb", "3": "adjective", "4": "noun"}, hint: "Look for the subject, how the action is done, the action itself, and what describes the things.", explanation: "Satellites is a noun (things), continuously is an adverb (how they capture), capture is a verb (action), detailed is an adjective (describes images), and images is a noun (things)!" },

// Story 155: Secrets of the Pyramids (O) - Nonfiction
// IDs 2927-2938
            { id: 2927, storyId: 155, category: "theme", type: "multiple", question: "What is the main theme of 'Secrets of the Pyramids'?", options: ["Ancient Egypt was a boring civilization", "The pyramids remain one of history's greatest mysteries despite modern research and technology", "Scientists have completely solved how the pyramids were built", "The pyramids are not very impressive structures"], correct: 1, hint: "Think about what the passage says about unsolved mysteries.", explanation: "The passage emphasizes that despite decades of research, many mysteries about the pyramids remain unsolved!" },
            { id: 2928, storyId: 155, category: "inference", type: "multiple", question: "Why does the author say the pyramids' precision 'seems impossible without lasers or computers'?", options: ["Ancient Egyptians actually had lasers", "The incredible accuracy of the construction is hard to explain with ancient tools alone", "Modern builders could not replicate the pyramids", "Lasers were invented in ancient Egypt"], correct: 1, hint: "Think about the level of precision described and what tools were available then.", explanation: "The near-perfect leveling and alignment achieved with ancient tools is so impressive it seems to require modern technology!" },
            { id: 2929, storyId: 155, category: "vocabulary", type: "multiple", question: "What does 'cardinal' mean when the passage says the sides 'align almost exactly with cardinal directions'?", options: ["Related to the red bird called a cardinal", "The four main compass directions: north, south, east, and west", "Related to high-ranking leaders", "Random or unimportant directions"], correct: 1, hint: "Think about the main directions on a compass.", explanation: "'Cardinal directions' are the four main compass points--north, south, east, and west--and the pyramid aligns precisely with them!" },
            { id: 2930, storyId: 155, category: "sequence", type: "multiple", question: "According to the most accepted theory, how were the stone blocks moved?", options: ["They were carried by elephants to the construction site", "Workers dragged stones up ramps using wooden sledges and water to reduce friction", "They were floated through underground rivers", "Aliens transported them using advanced technology"], correct: 1, hint: "The passage describes what most archaeologists believe about how stones were moved.", explanation: "Most archaeologists believe workers dragged stones up massive ramps using wooden sledges and water to reduce friction!" },
            { id: 2931, storyId: 155, category: "character", type: "multiple", question: "What perspective do archaeologists bring to studying the pyramids?", options: ["They believe the pyramids are not worth studying", "They use evidence and new discoveries to build theories about pyramid construction", "They have given up trying to explain how the pyramids were built", "They only study the outside of the pyramids"], correct: 1, hint: "Think about how the passage describes archaeologists' approach and recent discoveries.", explanation: "Archaeologists use evidence like the 2013 papyrus discovery and cosmic ray scanning to build and test theories!" },
            { id: 2932, storyId: 155, category: "main_idea", type: "multiple", question: "What is the main idea of 'Secrets of the Pyramids'?", options: ["The Great Pyramid's incredible construction and remaining mysteries continue to puzzle researchers", "The pyramids were easy to build with ancient tools", "All mysteries about the pyramids have been solved", "The pyramids are located in the desert"], correct: 0, hint: "What is the passage mainly about?", explanation: "The passage focuses on the amazing statistics of pyramid construction and the mysteries that still remain unsolved!" },
            { id: 2933, storyId: 155, category: "cause_effect", type: "multiple", question: "What has caused hidden chambers in the pyramid to be discovered recently?", options: ["Workers accidentally broke through a wall", "Cosmic ray scanning technology revealed them", "Tourists found a secret entrance", "Archaeologists read about them in ancient texts"], correct: 1, hint: "The passage mentions a modern technology used to find hidden spaces.", explanation: "Hidden chambers were discovered through cosmic ray scanning, a modern technology that can see inside solid structures!" },
            { id: 2934, storyId: 155, category: "compare_contrast", type: "multiple", question: "How does the passage contrast ancient Egyptian tools with the precision they achieved?", options: ["Ancient tools were highly advanced and easily explain the precision", "The passage doesn't mention any contrast", "The precision seems impossible without modern technology, yet they achieved it with ancient methods", "Modern tools produce less precise results than ancient ones"], correct: 2, hint: "Think about the near-perfect leveling and alignment described.", explanation: "The passage contrasts the lack of modern technology with incredibly precise results like 2.1 cm variation across 13 acres!" },
            { id: 2935, storyId: 155, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["The pyramids are the most beautiful structures ever built", "Ancient Egyptians were smarter than modern engineers", "The Great Pyramid contains approximately 2.3 million stone blocks", "The pyramids will never be fully understood"], correct: 2, hint: "Which statement uses a specific number that can be verified?", explanation: "The passage states the Great Pyramid 'contains approximately 2.3 million stone blocks'--a specific, verifiable fact!" },
            { id: 2936, storyId: 155, category: "author_purpose", type: "multiple", question: "Why did the author include the detail about the 2013 papyrus document?", options: ["To show that new evidence continues to be discovered about the pyramids", "To prove that ancient Egyptians could write", "To explain how paper was invented", "To show that boats existed in ancient times"], correct: 0, hint: "How does this recent discovery relate to the passage's theme of ongoing mystery?", explanation: "The 2013 papyrus shows that even after 4,500 years, new evidence about pyramid construction is still being found!" },
            { id: 2937, storyId: 155, category: "text_structure", type: "multiple", question: "How is 'Secrets of the Pyramids' organized?", options: ["As a step-by-step guide to building a pyramid", "By presenting the amazing statistics, then construction theories, then remaining mysteries", "As a chronological history of ancient Egypt", "As a debate between scientists who disagree"], correct: 1, hint: "Notice how the passage moves from facts to theories to unsolved questions.", explanation: "The passage is organized from impressive statistics, to construction theories, to mysteries that remain unsolved!" },
            { id: 2938, storyId: 155, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Workers dragged stones up massive ramps using wooden sledges.", answers: {"0": "noun", "1": "verb", "2": "noun", "4": "adjective", "5": "noun"}, hint: "Look for who does the action, the action itself, the objects, and what describes them.", explanation: "Workers is a noun (people), dragged is a verb (action), stones is a noun (things), massive is an adjective (describes ramps), and ramps is a noun (things)!" },

// Story 156: The Making of an Olympian (O) - Nonfiction
// IDs 2939-2950
            { id: 2939, storyId: 156, category: "theme", type: "multiple", question: "What is the main theme of 'The Making of an Olympian'?", options: ["Anyone can easily become an Olympic athlete", "Becoming an Olympian requires extraordinary dedication, sacrifice, and support over many years", "Only naturally talented people can become athletes", "Olympic athletes don't need coaches or trainers"], correct: 1, hint: "Think about everything the passage says athletes must invest.", explanation: "The passage shows that becoming an Olympian takes a decade or more of intense training, sacrifice, and support from many people!" },
            { id: 2940, storyId: 156, category: "inference", type: "multiple", question: "Why do gymnasts, swimmers, and figure skaters start training earlier than athletes in other sports?", options: ["These sports are easier than others", "Their sports reward skills developed before puberty", "These athletes are naturally more talented", "These sports don't require much practice"], correct: 1, hint: "The passage gives a specific reason related to physical development.", explanation: "The passage states these sports 'reward skills developed before puberty,' so athletes must start training very young!" },
            { id: 2941, storyId: 156, category: "vocabulary", type: "multiple", question: "What does 'protocols' mean when the passage mentions 'recovery protocols'?", options: ["Types of sports equipment", "Established procedures and routines", "Athletic competitions", "Dietary supplements"], correct: 1, hint: "The passage lists cryotherapy, massage, and monitored rest as examples.", explanation: "'Protocols' means established procedures or routines--recovery protocols are the specific methods athletes use to heal and rest!" },
            { id: 2942, storyId: 156, category: "sequence", type: "multiple", question: "According to the passage, what is the typical progression of an Olympic athlete's career?", options: ["Start specialized training around age 6-7, train 20-30 hours weekly by age 12, spend a decade or more preparing", "Start training at age 16, compete within a year", "Begin with mental training, then physical training", "Train for one year, then try out for the Olympics"], correct: 0, hint: "Follow the ages and milestones mentioned in the passage.", explanation: "Athletes begin specialized training by age 6-7, train 20-30 hours weekly by age 12, over a journey spanning a decade or more!" },
            { id: 2943, storyId: 156, category: "character", type: "multiple", question: "What do sports psychologists help Olympic athletes develop?", options: ["Better physical strength and speed", "Mental toughness, visualization techniques, and strategies for handling pressure", "Cooking skills for proper nutrition", "Social media presence and fame"], correct: 1, hint: "The passage specifically lists what sports psychologists help with.", explanation: "Sports psychologists help athletes develop 'mental toughness, visualization techniques, and strategies for handling pressure'!" },
            { id: 2944, storyId: 156, category: "main_idea", type: "multiple", question: "What is the main idea of 'The Making of an Olympian'?", options: ["The journey to becoming an Olympic athlete is incredibly demanding, requiring years of training, money, and sacrifice", "Olympic athletes are born with natural talent and don't need to train", "Injuries never happen to Olympic athletes", "Only wealthy families can produce Olympic athletes"], correct: 0, hint: "What does the passage emphasize about the overall Olympic journey?", explanation: "The passage shows the enormous demands of the Olympic journey: years of intense training, huge costs, and constant injury risk!" },
            { id: 2945, storyId: 156, category: "cause_effect", type: "multiple", question: "What is one effect of training 20 to 30 hours weekly by age twelve?", options: ["Athletes become famous immediately", "It affects education, friendships, and family relationships", "Athletes earn large salaries", "It guarantees a spot on the Olympic team"], correct: 1, hint: "The passage mentions what intensive training schedules affect.", explanation: "The passage states that 'this intensive schedule affects education, friendships, and family relationships'!" },
            { id: 2946, storyId: 156, category: "compare_contrast", type: "multiple", question: "How does the passage contrast the physical and mental aspects of Olympic training?", options: ["Physical training is the only part that matters", "Physical training is described alongside essential mental preparation by sports psychologists", "Mental training is more important than physical training", "Physical and mental training are completely separate and unrelated"], correct: 1, hint: "The passage says physical training is 'only part of the equation.'", explanation: "The passage states that physical training is 'only part of the equation' and emphasizes mental preparation is equally important!" },
            { id: 2947, storyId: 156, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Olympic athletes have the hardest jobs in the world", "Olympic training is the most rewarding experience possible", "Olympic training can cost families $50,000 to $100,000 annually", "Every young athlete should try to become an Olympian"], correct: 2, hint: "Which statement provides a specific, verifiable number?", explanation: "The passage states that 'Olympic training can cost families $50,000 to $100,000 annually'--a specific financial fact!" },
            { id: 2948, storyId: 156, category: "author_purpose", type: "multiple", question: "Why did the author include the detail about 'one wrong landing, one torn ligament'?", options: ["To discourage young athletes from trying sports", "To show how fragile an Olympic dream can be despite years of preparation", "To explain how ligaments work in the human body", "To promote injury prevention products"], correct: 1, hint: "What point is the author making about the risks athletes face?", explanation: "The author shows that years of preparation can be ended by a single injury, highlighting how fragile the Olympic dream is!" },
            { id: 2949, storyId: 156, category: "text_structure", type: "multiple", question: "How is 'The Making of an Olympian' organized?", options: ["As a biography of one specific Olympic athlete", "By covering different aspects of Olympic preparation: physical training, mental preparation, finances, and injury risk", "As a debate about whether the Olympics should continue", "In chronological order of Olympic Games history"], correct: 1, hint: "Notice how each section covers a different aspect of the Olympic journey.", explanation: "The passage is organized by topic--physical training, mental preparation, financial costs, and injury risks!" },
            { id: 2950, storyId: 156, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Coaches analyze video footage frame by frame, seeking tiny improvements.", answers: {"0": "noun", "1": "verb", "2": "adjective", "3": "noun"}, hint: "Look for who does the action, the action itself, what describes the thing, and the thing.", explanation: "Coaches is a noun (people), analyze is a verb (action), video is an adjective (describes footage), and footage is a noun (thing)!" },

// Story 157: Food Deserts in America (O) - Nonfiction
// IDs 2951-2962
            { id: 2951, storyId: 157, category: "theme", type: "multiple", question: "What is the main theme of 'How Bridges Are Built'?", options: ["Bridges are simple structures that anyone can build", "Different bridge designs solve different engineering challenges, showing human creativity", "Only suspension bridges are useful in modern times", "Bridge building has not changed in thousands of years"], correct: 1, hint: "Think about why engineers use different designs for different situations.", explanation: "The passage shows that engineers creatively use different bridge designs depending on the span, weight, and conditions they need to handle!" },
            { id: 2952, storyId: 157, category: "inference", type: "multiple", question: "Why might engineers choose an arch bridge over a beam bridge for a long span?", options: ["Arch bridges are always cheaper to build", "The curved shape of an arch distributes weight more effectively over longer distances", "Beam bridges cannot be built over water", "Arch bridges look more attractive to drivers"], correct: 1, hint: "Think about why beam bridges work best for shorter distances.", explanation: "The passage explains that beam bridges need stronger beams for longer spans, while arch bridges distribute weight along the curve, making them better for longer distances!" },
            { id: 2953, storyId: 157, category: "vocabulary", type: "multiple", question: "What does 'suspension' mean when describing a suspension bridge?", options: ["A bridge that sits flat on the ground", "A bridge where the roadway hangs from cables attached to towers", "A bridge that can be raised and lowered", "A bridge made entirely of concrete"], correct: 1, hint: "Think about the word 'suspend,' which means to hang from above.", explanation: "'Suspension' comes from 'suspend,' meaning to hang -- in a suspension bridge, the roadway is suspended from cables hanging from tall towers!" },
            { id: 2954, storyId: 157, category: "sequence", type: "multiple", question: "According to the passage, what order does bridge construction follow?", options: ["Build first, design later, then test for safety", "Choose materials, skip planning, and start building immediately", "Engineers consider factors, design using computer models, then construction workers build", "Construction workers decide the design while building"], correct: 2, hint: "Think about the planning and building process described in the passage.", explanation: "Engineers first consider factors like weight and wind, then use computer models to test designs, and finally construction workers build the bridge!" },
            { id: 2955, storyId: 157, category: "character", type: "multiple", question: "What perspective does the author present about bridge engineers?", options: ["Engineers make simple, straightforward decisions about bridges", "Engineers must be creative problem-solvers who consider many complex factors", "Engineers only follow old designs without innovation", "Engineers care more about appearance than safety"], correct: 1, hint: "Think about all the factors engineers must consider.", explanation: "The author shows that engineers must consider weight, wind, temperature, earthquakes, and more, requiring creative problem-solving!" },
            { id: 2956, storyId: 157, category: "main_idea", type: "multiple", question: "What is the main idea of 'How Bridges Are Built'?", options: ["Engineers use different bridge designs to solve different challenges, combining science and creativity", "The Golden Gate Bridge is the only important bridge in the world", "Bridges are all built the same way regardless of location", "Ancient bridges were better than modern ones"], correct: 0, hint: "What is the passage mainly about?", explanation: "The passage explains how different bridge types work, what factors engineers consider, and how science and creativity combine in bridge design!" },
            { id: 2957, storyId: 157, category: "cause_effect", type: "multiple", question: "What causes materials in a bridge to expand and contract?", options: ["The weight of vehicles crossing the bridge", "Wind pushing against the bridge structure", "Temperature changes that affect the materials", "Rain and moisture weakening the structure"], correct: 2, hint: "The passage mentions a specific factor that makes materials change size.", explanation: "Temperature changes cause bridge materials to expand when hot and contract when cold, which engineers must account for in their designs!" },
            { id: 2958, storyId: 157, category: "compare_contrast", type: "multiple", question: "How do beam bridges and suspension bridges compare?", options: ["Beam bridges handle longer spans than suspension bridges", "Both types use cables hanging from towers", "Beam bridges are simplest and best for short spans, while suspension bridges handle the longest spans using cables and towers", "There is no meaningful difference between the two types"], correct: 2, hint: "Compare what the passage says about each bridge type's strengths.", explanation: "Beam bridges are the simplest design for shorter distances, while suspension bridges use cables and towers to span the longest distances!" },
            { id: 2959, storyId: 157, category: "fact_opinion", type: "multiple", question: "Which of these is a FACT from the passage?", options: ["Suspension bridges are the most beautiful type of bridge", "The Golden Gate Bridge is the best bridge ever built", "The Golden Gate Bridge's cables contain enough wire to circle the Earth three times", "Arch bridges are more interesting than beam bridges"], correct: 2, hint: "Which statement provides specific, verifiable information?", explanation: "The passage states that the Golden Gate Bridge's cables contain enough wire to circle the Earth three times -- a specific, verifiable fact!" },
            { id: 2960, storyId: 157, category: "author_purpose", type: "multiple", question: "Why did the author include the example of the Golden Gate Bridge?", options: ["To argue that San Francisco has the best bridges", "To provide a familiar, real-world example that helps readers understand suspension bridges", "To compare California bridges to bridges in other states", "To explain why all bridges should be painted red"], correct: 1, hint: "How does mentioning a famous bridge help the reader?", explanation: "The Golden Gate Bridge is a well-known example that helps readers visualize and understand how suspension bridges work!" },
            { id: 2961, storyId: 157, category: "text_structure", type: "multiple", question: "How is 'How Bridges Are Built' organized?", options: ["As a story about building one specific bridge", "By describing different bridge types and then explaining the factors engineers consider", "As a timeline of bridge construction throughout history", "As a debate about which bridge type is best"], correct: 1, hint: "Notice how the passage moves from bridge types to engineering considerations.", explanation: "The passage first describes three bridge types (beam, arch, suspension), then explains the factors engineers must consider when designing any bridge!" },
            { id: 2962, storyId: 157, category: "grammar", type: "highlight", question: "Identify the parts of speech for the highlighted words.", sentence: "Engineers carefully design strong bridges for busy communities.", answers: {"0": "noun", "1": "adverb", "2": "verb", "3": "adjective", "4": "noun"}, hint: "Look for who does the action, how they do it, the action itself, and what describes the things.", explanation: "Engineers is a noun (people), carefully is an adverb (how they design), design is a verb (action), strong is an adjective (describes bridges), and bridges is a noun (things)!" },
